### ISSUE TITLE
How to listen to 'connected" and "disconneted" events?

### ISSUE THREAD

**Issue by garubi** [djipco/webmidi#103]
Hallo, I would like to intercept the 'connected' and 'disconnected' events, so that I can alert the user.

Since I'm still learning javascript I can't understand how I can "listes" to those events.
I've done a number o try like
`	navigator.addEventListener("connected", function(){
		alert('connected');
});`

`	WebMidi.addEventListener("connected", function(){
		alert('connected');
});`

but none of them is correct.
Can you provide some example?

Thank you!

**Comment by djipco** [comment]
The correct way to do this is to add a listener to the `WebMidi` object:

```javascript
WebMidi.addListener("connected", e => {
  console.log("Device connected: " + e.port.name, e);
});
```

Of course, this needs to be done after enabling WebMidi with `WebMidi.enable()`.

**Comment by garubi** [comment]
Thank you!
