### ISSUE TITLE
Very minor documentation error

### ISSUE THREAD

**Issue by PlatformSeven** [djipco/webmidi#104]
Firstly, many thanks for the brilliant code! I thought I'd mention a small typo in the API documentation: under the 'Input Class' > 'Methods' > 'Channel-specific MIDI events' section the link to NRPN is displayed as 'pitchbend' - so there appears to be 2 'pitchbend' links, when in fact one of them is to NRPN. As I say, very minor, just a little confusing.

**Comment by djipco** [comment]
Thank you for reporting this.
Fixed.
