### ISSUE TITLE
Some help with typescript

### ISSUE THREAD

**Issue by tamueller** [djipco/webmidi#105]
Hi,
I'm trying to get webmidi to work with typescript, but until now I've failed (I'm new to typescript, npm and packaging though). I installed webmidi using npm, but when I use:

```
import * as webmidi from "webmidi";
WebMidi.enable(function (err) {
  if (err) {
    console.log("WebMidi could not be enabled.", err);
  } else {
    console.log("WebMidi enabled!");
  }
});

```

I get an error that WebMidi is not defined, and when I try webmidi.enable it tells me that webmidi.enable is not a function. I tried different tools (gulp, parcel, webpackage) but can't find a solution.. does anyone have a simple working demo setup? Thanks for any help.

**Comment by djipco** [comment]
I am not a TypeScript user. However, there was some discussion that might help you in issue #82. Check it out and tell me if it helped.

**Comment by djipco** [comment]
@danigb has submitted a PR for the README.md file with more details on how to use WebMidi.js with TypeScript. I just merged it. Check out the [TypeScript](https://github.com/djipco/webmidi#typescript-support) section. It should help you!

P.S. Given the above, I'm going to close the issue. If you still have trouble, feel free to reopen it.
