### ISSUE TITLE
hasListener not working anymore ?

### ISSUE THREAD

**Issue by localhero44** [djipco/webmidi#106]
Hi,

Two years ago, I had started a MIDI project and I have used your nice JS library to simplify things.
It was working great.
Yesterday I have some time to work again on this project and I notice that I can't communicate with my MIDI device (based on Teensy).
The problem seems to be in the listener.
This line always returns false : 
`  console.log("Has event listener noteon: ", input.hasListener('noteon', "all", test) );`

I have tried to debug things and I think there is something strange at that line in the **hasListener** function : 
                `var listeners = that._userHandlers.channel[type][chNum];`
When I am in debug, I have seen that the variable listeners is undefined (with a break point just after this line).

Could you tell me if all is working fine for you ?
I use the latest version 2.5.1 and my browser is Chrome.

Regards
David

**Comment by djipco** [comment]
I just tested it and it works for me. Can you provide a full example that is not working for you so I can try it on my side?

**Comment by localhero44** [comment]
Hi,
Thanks for the answer.
Here is some simple code to just check the listeners :
```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>WebMidi</title>
    <link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css />
  </head>
  <body>
    <!-- Unit tests output container -->
    <div id="mocha" class="container">

      	<h1>WebMidi.js </h1>
	  	<div id=alert class="alert" role="alert"></div>
    </div>

    <!-- WebMidi -->
    <script src="https://cdn.jsdelivr.net/npm/webmidi"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.js"></script>
	<script>
$( document ).ready(function() {

	// Enable WebMidi.js
	WebMidi.enable(function (err) {

	if (err) {
		console.log("WebMidi could not be enabled.", err);
  	} else {
	    console.log("WebMidi & sysex enabled!");
  	}

  // Retrieving an output port/device using its id, name or index
  var output = WebMidi.getOutputByName("Teensy MIDI");
//  output = WebMidi.outputs[2];
  if(output == false) {
  	$('#alert').text('No Teensy ouput connected').addClass('alert-danger');
  	return false
  }
	
  // Retrieve an input by name, id or index
  var input = WebMidi.getInputByName("Teensy MIDI");
  if(input == false) {
  	$('#alert').text('No Teensy input connected').addClass('alert-danger');
  	return false
  }

  $('#alert').text('Connected to Teensy MIDI input').addClass('alert-success');

  // Listen for a 'note on' message on all channels
  input.addListener('noteon', "all",
    function (e) {
      console.log("Received 'noteon' message (" + e.note.name + e.note.octave + ").");
    }
  );
  console.log("Has event listener noteon: ", input.hasListener('noteon', "all", mytest) );

  // Listen to sysex message on all channels
  input.addListener('sysex', "all", function(e) {
     console.log("Received 'sysex' message.", e);
  });
  console.log("Has event listener sysex: ",  input.hasListener('sysex', "all", mytest) );

function mytest(e) {
      console.log("listener:[" + JSON.stringify(e) + "]");
    }
}, true); // true to enable sysex

}); // jquery ready
	</script>

  </body>
</html>
```
In the console I get : 
_WebMidi & sysex enabled!
index.html:54 Has event listener noteon:  **false**
index.html:60 Has event listener sysex:  **false_**

**Comment by djipco** [comment]
>Am I missing something ?

Yes. ;-) 

The 3rd parameter to `hasListener()` is the function to check for. `mytest` is not the function that was added by `addListener()`. To properly use `hasListener()`, you need to pass it the actual function that was added.

Hope that's clear.

**Comment by localhero44** [comment]
Ohhh thank you, it wasn't clear for me from the example.
It's working great now (je pense que je peux parler en français, merci beaucoup Jean-Philippe :) )
