### ISSUE TITLE
creating a loopback (midi in foward to midi out)

### ISSUE THREAD

**Issue by ffd8** [djipco/webmidi#109]
Curious how one could forward received messages to another device, perhaps a [simple loopback](https://www.w3.org/TR/webmidi/#a-simple-loopback).

Imagined it should just forward the entire midimessage...
Can listen to it here:
```
midiInput.addListener('midimessage', 'all', function(e){
	println(e); // e.data = just midi message to forward?
});
```

Then for sending out.. the `send()` [method API](http://djipco.github.io/webmidi/latest/classes/Output.html#method_send) doesn't seem to be wanting that midimessage, but rather a status, data and timestamp... perhaps a bug in the API is it mentions using the `sendSystemMessage()` method, which doeesn't exist anywhere in docs. Nevertheless, I tried sending the data like so: `midiOutput.sendSystemMessage(e.data)` and flooded my midi.. ha. 

Probably missing an obvious in the docs.. but perhaps a function could be `sendMidiMessage()` that is ready for the exact object that's given by the `midimessage` listener, with data + timestamp?

**Comment by ffd8** [comment]
Aha, figured it out:
```
midiInput.addListener('midimessage', 'all', function(e) {
	// println(e); // debug message
	// midiOutput.send(255, e.data); // doesn't work...
	midiOutput.send(255, [e.data[0], e.data[1], e.data[2]]); // works
});
```
Could you explain the first `status` param of `send()`? Curious if I can leave it at 255... or if it's possible to have the `midimessage` listener also include the status to forward. 

Strangely I couldn't drop the `e.data` array into the `data` param of `send()`, but instead had to create a new array with each value. When trying to include the `e.data` array, I got the following error: 
```
Uncaught TypeError: Failed to execute 'send' on 'MIDIOutput': Unexpected status byte at index 1 (128).
    at Output.send (VM32 webmidi.min.js:31)
    at VM33 about:srcdoc:251
    at VM32 webmidi.min.js:31
    at Array.forEach (<anonymous>)
    at Input._onMidiMessage (VM32 webmidi.min.js:31)
```

**Comment by djipco** [comment]
> Could you explain the first status param of send()?

The first parameter of the `send()` method is the **status** byte of the MIDI message. The **status** byte contains 2 informations: the first 4 bits are used for the command (**note on**, **control change**, etc.) and the last 4 bits are used for the channel (0-15). You can check out the syntax of MIDI messages in [Table 1 - Summary of MIDI Messages](https://www.midi.org/specifications/item/table-1-summary-of-midi-message) on [midi.org](https://www.midi.org/).

So, if you wanted to forward the message, you would use: 

```js
midiOutput.send(e.data[0], [e.data[1], e.data[2]]);
```

Beware that most MIDI messages require 1 or 2 bytes of data but not all. Some messages only use the status byte (e.g. **tune request**, **reset**, etc.) and no data byte. This means that `e.data[1]` and `e.data[2]` will not always be present

> Curious if I can leave it at 255...

If you look at the table linked above, a **status** of 255 is the **reset** MIDI message. Probably not what you want.

> Strangely I couldn't drop the e.data array into the data param of send(), but instead had to create a new array with each value. 

That's a very interesting point. Here, the library is following what the Web MIDI API does. According to the spec, the [MIDIMessageEvent](https://www.w3.org/TR/webmidi/#idl-def-MIDIMessageEvent) contains only 2 properties: `data` and `receivedTime`. It does not make any kind of distinction between the status byte and the actual data byte(s).

It might be a good idea for WebMidi.js to include `statusByte` and `dataBytes` properties that isolate the **status** byte and the **data** bytes (if any) of the incoming MIDI message. It actually would make a lot of sense. This is the kind of niceties this library is meant to provide. I added it to my [to do list](https://github.com/djipco/webmidi/wiki) for v3.

**Comment by ffd8** [comment]
> It might be a good idea for WebMidi.js to include statusByte and dataBytes properties that isolate the status byte and the data bytes (if any) of the incoming MIDI message

That sounds like a great plan (so the `dataBytes` would be an empty array in the case of no info sent.. but object still present, so one could just listen for a message and pass that object to the `send()`. Thanks for clarifying the `send()` params above. I got lucky that it was working since only playing with notes on/off at the moment.

**Comment by djipco** [comment]
> so the `dataBytes` would be an empty array in the case of no info sent..

I think it would be more appropriate for `dataBytes` to be `undefined` when no data bytes have been received. This would not prevent you from passing it to `send()` (it would simply ignore it).

**Comment by ffd8** [comment]
Hm, wouldn't that require every implementation of it to check if it's defined? Haha probably makes sense in most cases.. in this particular loopback instance, would be nice if the `send()` function was ready for an empty array (or whatever a non `dataBytes` looks like).

**Comment by djipco** [comment]
> Hm, wouldn't that require every implementation of it to check if it's defined?

Nope. You can happily pass an undefined value to send and it will not complain.

> would be nice if the send() function was ready for an empty array (or whatever an empty dataBytes looks like)

It's already the case! Cheers!
