### ISSUE TITLE
'nrpn' not included in type definitions for InputEvents

### ISSUE THREAD

**Issue by disambiguator** [djipco/webmidi#110]
Hi! Thanks for an awesome library and really great documentation.

It looks like `nrpn` is a valid value for a channel event shown [here](https://github.com/djipco/webmidi/blob/master/src/webmidi.js#L161) but isn't incliuded in the type definitions https://github.com/djipco/webmidi/blob/master/webmidi.d.ts#L213.

Therefore,  TypeScript reports an error for:
```
      input.addListener('nrpn', 'all', (e) => {
        console.log(e);
      });
```

**Comment by djipco** [comment]
Thanks for reporting this. In all honesty, I am not a TypeScript user and do not have much knowledge about type definitions. The `webmidi.d.ts` file was contributed by @mmmveggies. 

Would you be able to contribute a PR to fix this?

**Comment by disambiguator** [comment]
Ah. I don't know enough about NPRN to really do that, I don't think. :( I'm new to MIDI and ended up not being able to use it anyways. If I get back to this later, I'll try to do this for you, appreciate the response.

**Comment by djipco** [comment]
Don't worry about it. It's really more of a TypeScript issue. I decided to not officially support TypeScript in v2 because I'm not familiar enough with it. Version 3, which I'm working on, should have  a fully working type definition file.

**Comment by djipco** [comment]
Unless somebody can come forward with a PR, I will close the issue for now. TypeScript support is planned for v3.
