### ISSUE TITLE
getInputById(...).hasListener is not a function

### ISSUE THREAD

**Issue by realmayus** [djipco/webmidi#112]
I want my "Start Listening to MIDI" button to be disabled when the current input already has a listener.

```jsx
<button onClick={addMidiListener} disabled={WebMidi.enabled && selectedMidiDevice !== null && WebMidi.getInputById(selectedMidiDevice).hasListener("noteoff", "all", triggerRelease)}>Listen for MIDI</button>
```

The midi listener is registered here: (addMidiListener gets called when the user clicks on the button)
```jsx
    const addMidiListener = () => {
        let input = WebMidi.getInputById(selectedMidiDevice);
        input.addListener("noteon", "all", e => {
            console.log("Received 'noteon' message (" + e.note.name + e.note.octave + ").");
            console.log(e.rawVelocity);
            sampler.current.triggerAttack(e.note.name + e.note.octave)
        });
        input.addListener("noteoff", "all", triggerRelease)
    };

    const triggerRelease = (e) => {
        sampler.current.triggerRelease(e.note.name + e.note.octave)
    };
```
However, react shows me this error:
`TypeError: webmidi__WEBPACK_IMPORTED_MODULE_3___default.a.getInputById(...).hasListener is not a function`. It points to the line in the JSX where I defined the HTML button (first code snippet).

Edit: actually, it points to this line :thinking: 
![](https://i.imgur.com/c24fIRV.png)

Am I missing something?

**Comment by djipco** [comment]
Unfortunately, I do not use React (this is React code, right?) so I'm afraid I cannot really help you with this.

**Comment by djipco** [comment]
Since there hasn't been any updates on this issue, I will close it for now. Feel free to reopen if needed.
