### ISSUE TITLE
velocity range to 127 when output.playNote

### ISSUE THREAD

**Issue by Vexcited** [djipco/webmidi#113]
How to play e.g. output.playNote(note, 6, {velocity: 1 to 127}); ? Like in DAWs
it can help me for doing launchpad lightshow from browser.

**Comment by djipco** [comment]
I am sorry but I do not understand your question. The velocity is the initial "attack" of the note, you cannot increase it while the note is playing... Can you please clarify?

**Comment by Vexcited** [comment]
Yes I can,

in my JS script, i want to play manually 

```
// When a MIDI key is pressed :
input.addListener('noteon', "all",
   function (e) {
                        /*
                         When i change the velocity, the color on my Launchpad change ! 
                         On velocity: 1, it's orange ;
                         on velocity 0.5, its green.
                        */
                        output.playNote(e.note.name + e.note.octave, 6, {velocity: 1}); 
                        locateSample(e.note.name + e.note.octave); // <- this play the sample note +'.wav'
     }
);
```

I want something like in my DAW, something to 1 to 127, (i dont know if its possible on this api ;-;)

![Annotation 2020-06-04 132934](https://user-images.githubusercontent.com/59152884/83751745-a4814900-a667-11ea-98a7-83fa64d42608.png)

**Comment by Vexcited** [comment]
Oh I think I understand !

When I do (a velocity in ableton) eg: 56/127 i get 0,44.
If I play this velocity in my code so `output.playNote(e.note.name + e.note.octave, 6, {velocity: 0.44});`
The color will be the same in my browser as in my DAW !

Just divide the velocity in the DAW by 127 and I've found the velocity for WebMIDI. !

**Comment by djipco** [comment]
The `playNote()` method does allow you to specify the attack velocity. You can do so with a value between `0` and `1` like this:

```javascript
output.playNote("C4", 6, {velocity: 1});
```
You can also use a raw velocity value (0-127) like so:

```javascript
output.playNote("C4", 6, {rawVelocity: true, velocity: 127});
```
For more details, you can check out the [documentation](https://webmidijs.org/docs/v2.5.1/classes/Output.html#method_playNote) for the `playNote()` method.
