### ISSUE TITLE
Cannot listen input from notes ['F6', 'G5', 'A4', 'B3', 'C#3', 'D#2', 'F1', 'G0']

### ISSUE THREAD

**Issue by Vexcited** [djipco/webmidi#114]
I own a Launchpad PRO and the MIDI Notes Values are like that:

![image](https://user-images.githubusercontent.com/59152884/84409371-a326c200-ac0d-11ea-88ef-f3f0a0b3f9bb.png)

The notes *89, 79, 69, 59, 49, 39, 29, 19* and **all the circles one**, WebMidi.js didn't recognise them whit input.addListener.
But when I output.playNote, they lights up !

My code:

![image](https://user-images.githubusercontent.com/59152884/84410659-58597a00-ac0e-11ea-8757-c0cd579fa7e8.png)

**Comment by Vexcited** [comment]
I've just seen that if I press on these buttons the message.data is different on WebMidi
![image](https://user-images.githubusercontent.com/59152884/84415952-ceacab00-ac13-11ea-84f7-d7fb7693635a.png)

Normal pad button: 
![image](https://user-images.githubusercontent.com/59152884/84415975-d8361300-ac13-11ea-8867-240d62f6c071.png)

**Comment by djipco** [comment]
The messages that start with `148` are regular `"noteon"` messages on channel 5. However, the messages that start with `180` are **control change** messages on channel 5. This means that your device does not treat all pads in the same way. To catch those messages, you can listen simply to the `"controlchange"` event. You can check the [documentation](http://webmidijs.org/docs/v2.5.1/classes/Input.html#event_controlchange) for more info.

**Comment by Vexcited** [comment]
Thanks it works !
