### ISSUE TITLE
MIDI Devices doesnt listed ok in Chrome

### ISSUE THREAD

**Issue by henriquegmatos** [djipco/webmidi#115]
Dear,

I noticed that in Chrome the device list does not show the names correctly

Input list using Chrome version 84 - 64 bits
0 in = MIDI
1 in = Focusrite USB MIDI [1]
2 in = MIDI
3 in = MIDI
4 in = Fast Track Pro MIDI In [0]
5 in = UMX 25 [1]
6 in = MIDI
7 in = MIDI
8 in = MIDI
9 in = MIDI
10 in = MIDI

Output list using Chrome version 84 - 64 bits
0 out = MIDI
1 out = MIDI
2 out = MIDI
3 out = MIDI
4 out = MIDI
5 out = MIDI
6 out = MIDI
7 out = MIDI
8 out = MIDI
9 out = MIDI
Oct 10 = UMX 25 [0]

The same application is showing names correctly in Microsoft EDGE

INPUT LIST Using EDGE version 83 - 64 bits
0 in = Fast Track Pro MIDI In
1 in = Yamaha MOXF6 / MOXF8-1
2 in = Yamaha MOXF6 / MOXF8-2
3 in = Yamaha MOXF6 / MOXF8-3
4 in = Yamaha MOXF6 / MOXF8-4
5 in = Yamaha MOXF6 / MOXF8-5
6 in = Automap MIDI
7 in = UMX 25
8 in = Focusrite USB MIDI
9 in = Automap Propellerhead Mixer
10 in = Automap Propellerhead

OUTPUT LIST Using EDGE version 83 - 64 bits
0 out = Fast Track Pro MIDI Out
1 out = Yamaha MOXF6 / MOXF8-1
2 out = Yamaha MOXF6 / MOXF8-2
3 out = Yamaha MOXF6 / MOXF8-3
4 out = Yamaha MOXF6 / MOXF8-4
5 out = Yamaha MOXF6 / MOXF8-5
6 out = Automap MIDI
7 out = UMX 25
8 out = Focusrite USB MIDI
9 out = Automap Propellerhead Mixer
10 out = Automap Propellerhead

NOTE: I also noticed that in both, do not present the MIDI output for the "Microsoft GS Wavetable Synth", however this is not relevant in my case.

Did you know this problem? There is a way to resolve it. Because in my application I would like to identify and select the port "Yamaha MOXF6 / MOXF8-1" automatically by code, but it would only work in EDGE since in Chrome I would not be able to identify it. Is it possible to resolve this in any way?

Thank you for developing the WEBMIDI component. I believe it will help me a lot.

Best regards

**Comment by djipco** [comment]
Can you paste the following code in the browser's console, press `ENTER` and tell me what you get ?

```javascript
navigator.requestMIDIAccess().then(midiAccess => {
    for (let input of midiAccess.inputs.values()) {
        console.log(input.name);
    }
});
```

**Comment by henriquegmatos** [comment]
![Chrome](https://user-images.githubusercontent.com/57631301/87691521-0b167e00-c761-11ea-93f2-9c55e8bb37c7.JPG)
![EDGE](https://user-images.githubusercontent.com/57631301/87691541-0fdb3200-c761-11ea-8c50-8b0b3d32391f.JPG)

OK. plaese get the capture files.

thanks.

**Comment by djipco** [comment]
This is what I suspected. WebMidi.js uses what the browser reports for the names of the devices. Therefore, there is not much I can do.

You should [file a bug report](https://bugs.chromium.org/p/chromium/issues/list) with the Chromium team. Once done, post the link here so I can track the progress.

**Comment by henriquegmatos** [comment]
Ok. Thanks

https://bugs.chromium.org/p/chromium/issues/detail?id=1106447

**Comment by djipco** [comment]
I subscribed to the bug report you submitted. This way, I will be notified when the bug is fixed and I will double-check that it does solve the problem for WebMidi.js also. Thanks for reporting this!
