### ISSUE TITLE
Sync code

### ISSUE THREAD

**Issue by henriquegmatos** [djipco/webmidi#119]
Hello Dear

Due the way to get data from input midi is a listener  function, I did not have success to create a single function to send a sysex message and receive the sysex data. I need to create a function like that:

Var receivedData = sendAndGetSysex( dataToSend)

The idea is, for instance, send a Id request to device and receive its data manufacture id using a single function.

Do you please have a example code to this kind of function? i try using async/await but I got no results.

Thank you for any help.

**Comment by djipco** [comment]
Per your last suggestion, I have already added a `getIdentity()` method to the [todo list for v3](https://github.com/djipco/webmidi/wiki#enhancements-for-upcoming-v3). This method would send an identity request and wait for the answer (using a promise).

Meanwhile, if you have usage-related questions, I highly encourage you to post them in the [Questions & Support](https://webmidijs.org/forum/) section of our new forum: https://webmidijs.org/forum/

By doing so, you will make it easier for others to help you and also help future users discover answers to your very question.

Cheers!
