### ISSUE TITLE
Is it possible to be notified if devices have changed?

### ISSUE THREAD

**Issue by cuinjune** [djipco/webmidi#121]
Hi, Is there any supported method that can notify me as soon as the list of input/output devices has changed?

Thanks in advance!

**Comment by djipco** [comment]
The `WebMidi` object dispatches `connected` and `disconnected` events when devices are connected or disconnected. There is a little more info in the [docs](https://webmidijs.org/docs/v2.5.1/classes/WebMidi.html#events).

P.S. When you have a question regarding usage, I invite you to submit it to the brand new [WebMidi.js forum](https://webmidijs.org/forum/). Cheers!

**Comment by cuinjune** [comment]
@djipco Thank you for your answer. But I don't understand how to use it.
I tried the following but doesn't work.

```
WebMidi.connected().then(function(e) {
            console.log("CONEECTED!!!");
    });
```

**Comment by djipco** [comment]
This is not how events work. To add a listener function to an event dispatched by the `WebMidi` object, you would use something like this:

```javascript
WebMidi.addListener("connected", function(e) {
  console.log(e);
});
```

I added this example to the [More Code Examples](https://github.com/djipco/webmidi/#more-code-examples) section of the GitHub README page.

**Comment by cuinjune** [comment]
@djipco Thank you so much! I just asked another question in the forum so please check.
