### ISSUE TITLE
Suggestion:  VirtualInterface

### ISSUE THREAD

**Issue by henriquegmatos** [djipco/webmidi#123]
Hello

I would like to suggest the inclusion of methods for working with virtual midi interfaces

Example:

```
WebMidi.createVirtual ('VirtualPort-1');
vOutputPort = WebMidi.getOutputByName ('VirtualPort-1');
vInputPort = WebMidi.getInputByName ('VirtualPort-1');
WebMidi.destroyVirtual ('VirtualPort-1');

```
This would be great for VST controls.

best regards

**Comment by djipco** [comment]
Thank you for the suggestion. Can I ask you to post it to the [Forum](https://webmidijs.org/forum/) instead (in the [Enhancement Proposals](https://webmidijs.org/forum/categories/enhancements) section). This will allow the community to discuss it while reserving GitHub for bugs and issues. Thanks!

**Comment by henriquegmatos** [comment]
Sure! Thanks.

**Comment by jpw** [comment]
Hi @djipco as a suggestion, it might be an idea to configure [issue templates](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) for this repo to ensure issues are filed appropriately, or instead opened on the forum.

**Comment by djipco** [comment]
> it might be an idea to configure [issue templates](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) for this repo to ensure issues are filed appropriately, or instead opened on the forum.

Great minds think alike. I setup templates a few days ago. Cheers!
