### ISSUE TITLE
A new question at forum

### ISSUE THREAD

**Issue by henriquegmatos** [djipco/webmidi#125]
Hello dear.

I would like to kindly ask you to check an issue I left on the Forum.

https://webmidijs.org/forum/discussion/25/checking-input-buffer#latest

Best Regards

**Comment by djipco** [comment]
There is no need to file an issue to report a post on the forum. I had seen your forum message but just didn't get around to respond yet.

**Comment by henriquegmatos** [comment]
Ok. Thank you very much
