### ISSUE TITLE
Web MIDI API error in Chrome 

### ISSUE THREAD

**Issue by soklamon** [djipco/webmidi#129]
Hey! I tried it in Chrome Version 87.0.4280.88 (Official Build) (x86_64) and get the error: "The Web MIDI API is not supported in this browser." 
Any suggestions?

**Comment by djipco** [comment]
I just tried WebMidi.js v2.5 and 3.0a and both worked for me with that same Chrome version (on macOS). Can you provide more info about the version you are using and the environment you are using it in? And perhaps sample code that triggers the error?

**Comment by djipco** [comment]
Since I've not heard back, I'm going to close this. If you ever want to submit the requested info, feel free to re-open. Cheers!
