### ISSUE TITLE
Getting a console error when note C4 is released. 

### ISSUE THREAD

**Issue by chrisspring215** [djipco/webmidi#130]
Getting a console error when note C4 is released.

`Uncaught TypeError: Cannot read property 'rate' of undefined
    at js.js:119
    at webmidi:31
    at Array.forEach (<anonymous>)
    at Input._parseChannelEvent (webmidi:31)
    at Input._onMidiMessage (webmidi:31)`

**Comment by djipco** [comment]
Can you send a small code sample that triggers the problem?

**Comment by djipco** [comment]
Since I haven't heard back, I'm going to close this. If you ever decide to submit a code sample, feel free to re-open. Cheers!
