### ISSUE TITLE
`removeListener` not working, listeners still existing even after `WebMidi.disable()`

### ISSUE THREAD

**Issue by PromethiumL** [djipco/webmidi#131]
**Describe the bug and how to reproduce it**
1. `removeListener` executed without error, but listeners for `noteon` still work.
2. Even after `WebMidi.disable()`, where `WebMidi.enabled === false`, `noteon` was still listened.

**Environment:**
 - Operating system: **Windows 10** 
 - Browser: tested on both **Edge 90.0.789.1 (Official build) dev (64-bit)** and **Chrome 88.0.4324.150 (Official Build) (64-bit) (cohort: Stable)**
 - Library version **webmidi@2.5.1**

**Additional context**
Minimum code for reproducing:
```js
<script src="https://cdn.jsdelivr.net/npm/webmidi@2.5.1"></script>
<html>
<body onload="initWebMidi()">
<button onclick="removeListener()">RemoveListener</button>
</body>
</html>

<script>

  function noteOn (e) {
    console.log('noteon event')
  }

  function handler (err) {
    if (err) {
      console.error(err)
    } else {
      const input = WebMidi.getInputByName('My MIDI Keyboard')
      input.addListener('noteon', 'all', noteOn)
      console.log('listener added.')
      console.log('Enabled.')
    }
  }

  function initWebMidi () {
    WebMidi.enable(handler)
  }

  function removeListener () {
    WebMidi.removeListener()
    WebMidi.disable()
    console.log('all listeners should be removed.')
  }
</script>
```
Actions: 
1. When page loaded, press keys on the midi keyboard.
2. Click `RemoveListener` button
3. Press some keys on the midi keyboard.

Expected output on console:
```
listener added.
Enabled.
noteon event
all listeners should be removed.
```
Actual output:
```
listener added.
Enabled.
noteon event
all listeners should be removed.
noteon event
```

**Comment by djipco** [comment]
You are right.

The `WebMidi.disable()` method should have cleared all listeners on `WebMidi` and `Input` objects. Version 2.5.2 (available right now) fixes this problem. Thank you for reporting the problem and being thorough while doing so. 

P.S. Please note that `WebMidi.removeListener()` only clears listeners added to the `WebMidi` object itself.
