### ISSUE TITLE
No typescript definitions for WebMidi 3

### ISSUE THREAD

**Issue by digable1** [djipco/webmidi#134]
There's no index.d.ts in this branch.

And if I'm reading it right, the definitions in version <3 is not correct anymore because WebMidi.enable is promise-based.

Furthermore, the definition in @types/webmidi is really incorrect, and that causes confusion for newbies like me.

**Comment by djipco** [comment]
> There's no index.d.ts in this branch.

This is correct. Version 3 is in alpha and the final API may still change. This is why I have not started work on type definitions. In fact, I do not use TypeScript and will probably ask someone who does to help me with this. This is very tedious and boring work.

> the definitions in version <3 is not correct anymore because WebMidi.enable is promise-based.

`WebMidi.enable()` will be promise-based in the next version (v3) but is not in the current production version (2.5.x).

> the definition in @types/webmidi is really incorrect, and that causes confusion for newbies like me.

The definitions in @types/webmidi should be correct for the current production version (2.5.x). If you find errors, feel free to submit an issue.

If you want to take a stab at a definition file for version 3, I'd welcome a pull request. 

Cheers!

**Comment by digable1** [comment]
Oops!

I am starting a new personal initiative leveraging webmidi.  And made a calculation reducing the extensions necessary for FireFox was important enough to start with it and hope that the work was far enough along.  Also, working with Node is a significant improvement.

I'll come back to v3 when it's wired for Typescript, with example that includes import and bundling (webpack for me).

Sorry, I don't have the bandwidth right now for the definition file stab.  If there's still a gap when/if I get the bandwidth, I may try at that time.

**Comment by djipco** [comment]
As you can see in the wiki, various usage examples are on the roadmap for v3. Cheers!

**Comment by digable1** [comment]
I do see - now that I looked at the wiki.  Just keeping consistent with my propensity for jumping guns.  This looks nice - look forward to the future.
