### ISSUE TITLE
Please provide a list of midi message type that are supported

### ISSUE THREAD

**Issue by elmcapp** [djipco/webmidi#136]
Can you provide a list which contains the type of midi messages that are supported for input and out in the documentation. Example noteon, controlchange. Also would be nice if you can provide the data we would receive or send for example

noteon: note, channel, velocity 
controlchange: value, channel, velocity 

I am not sure what midi message are supported

**Comment by djipco** [comment]
All standard MIDI 1.0 messages are supported.

The inbound MIDI messages that can be listened for on an input can be viewed at:
https://webmidijs.org/docs/v2.5.2/classes/Input.html#method_addListener

The methods available to send messages are here:
https://webmidijs.org/docs/v2.5.2/classes/Output.html

**Comment by djipco** [comment]
Since I haven't heard back, I will close this issue. If you ever need clarifications, feel free to reopen it or ask a question on the [Forum](https://webmidijs.org/forum/).

**Comment by abulka** [comment]
Above links are broken. Try 
- https://webmidijs.org/api/classes/Input or even better https://webmidijs.org/api/classes/InputChannel#events 
- https://webmidijs.org/api/classes/Output/

**Comment by djipco** [comment]
I fixed the link in my message above. Those were for v2.5.3. The links provided y @abulka (thanks!) are for v3.0.
