### ISSUE TITLE
receiving messages from all midi devices

### ISSUE THREAD

**Issue by elmcapp** [djipco/webmidi#138]
Is there  a way we can listen for midi messages coming from any device connected to the computer without needing to select a midi input device to listen for.  Basically if 2 midi devices are connected to the computer we can listen to both devices same time 

`var input = WebMidi.getInputByName("ALL CONNECTED MIDI DEVICES");

input.addListener('pitchbend', "all", function(e) {
    console.log("Pitch value: " + e.value);
});`

**Comment by takyano** [comment]
WebMidi.inputs is an array of inputs that you might be looking for.

**Comment by elmcapp** [comment]
Yes I know that WebMidi.inputs is an array of midi inputs but what I am hoping to do is add an event listen that will listen to all midi message across all midi devices. Lets say that I have 3 midi controllers I would like to console log all "note on" messages from all 3 midi controllers. Basically I don't want to monitor 1 input device but I want to monitor all i midi devices

**Comment by takyano** [comment]
I haven't seen a global message listener method.

You can loop over the inputs array and add a listener to each input for each type of message that you want to monitor.

	for( let a = 0; a < WebMidi.inputs.length; a++ )
	{
		WebMidi.inputs[ a ].addListener( 'controlchange', 'all', function( e ) {
			console.log( `Control Change (${e.target.name}): ${e.value}` );
		});
		WebMidi.inputs[ a ].addListener( 'noteon', 'all', function( e ) {
			console.log( `Note On (${e.target.name}): ${e.note.name}` );
		});
	}

**Comment by djipco** [comment]
> Is there a way we can listen for midi messages coming from any device connected to the computer without needing to select a midi input device to listen for.

Currently, there is no way to automatically do what you describe. Of course, you can always add listeners to all devices like @takyano suggested.

Having said that, it might be interesting to add this functionality. Currently, in version 3.0.0-alpha.5, you can add listeners at the device level and at the channel level. I don't see why we couldn't do the same at the WebMidi.js level. I added this suggestion to the enhancements to evaluate in the [wiki](https://github.com/djipco/webmidi/wiki#enhancements-to-evaluate).
