### ISSUE TITLE
Port statechange events?

### ISSUE THREAD

**Issue by sbilstein** [djipco/webmidi#14]
Is that TODO in reference to a listener for MIDI inputs and outputs coming online and offline? Working on a project using that lib and would be interested in contributing.

**Comment by cotejp** [comment]
The `statechange` events dispatched by `MIDIAccess` are currently handled. However, the `statechange` events dispatched by `MIDIPort` are not. As far as I can tell, they are very similar. I have not had time to look at them in details but if you want to take a stab at it, that would be great!

**Comment by djipco** [comment]
To be absolutely clear, you can already listen to `connected` and `disconnected` events on the `WebMidi` object itself:

```javascript
WebMidi.addListener("disconnected", function (e) {
  console.log(e);
})
```
This will let you know when an existing device is being disconnected or when a new device is being connected. 

So, the only thing I could add is a `disconnected` event directly on the `Input` and `Output` objects.

**Comment by djipco** [comment]
I looked at this a little more carefully and it has implications which I'm not ready to delve into yet. Therefore, I'll keep this proposition in the to do list but I'm going to put this on ice for now.
