### ISSUE TITLE
WebMidi not working on automatic restart

### ISSUE THREAD

**Issue by elmcapp** [djipco/webmidi#140]
On macOS Platform using WebMidi, If a users close lid on laptop of course the computer shuts down. When they open the lid on the laptop the computer turns back on including any programs that was left open. The problem is WebMidi will no longer work into user close browser and reopen the browser containing WebMidi

**Comment by djipco** [comment]
I was able to confirm the problem. Unfortunately, it is not a straightforward and easy fix. I will have to change the way the `WebMidi.prototype._updateInputs()` method works. 

Thanks for reporting the issue @elmcapp! I will keep you posted with updates.

**Comment by djipco** [comment]
Unfortunately, I do not have the bandwidth to fix this in v2.5.x. I have added it to my [todo list](https://github.com/djipco/webmidi/wiki) for v3. Thanks again for reporting.

**Comment by elmcapp** [comment]
Sounds great. Is the version available for download now using npm
