### ISSUE TITLE
playnote sends the note 1 octave lower

### ISSUE THREAD

**Issue by jellohouse** [djipco/webmidi#145]
Version: "webmidi": "^2.5.2"

When I play a note it actually sends the note an octave lower.

For example if I'm playing D#2, then in Lightkey (a software which receives the midi signal) plays the cue on the note D#1

Has anyone else noticed this?
I saw other similar issues about octave offsets but on older versions of this package...

**Comment by djipco** [comment]
The MIDI spec does not specify the pitch for MIDI notes. So, different manufacturers use different references for note numbers.  For further information, you can read through [issue #42](https://github.com/djipco/webmidi/issues/42#issuecomment-395989430) where this was discussed.

**Comment by jellohouse** [comment]
Ohhh ok now I see... Thanks!!

I went with your proposed solution: `WebMidi.octaveOffset = -1`. 
Very elegant and works like a charm!
