### ISSUE TITLE
The requested module does not provide an export named 'default'

### ISSUE THREAD

**Issue by michaelcaterisano** [djipco/webmidi#146]
I'm trying out webmidi 2.5.2 in a typescript environment and am getting an error when importing webmidi like this: `import Webmidi from "webmidi";`. 

```
The requested module does not provide an export named 'default'
```

I also tried `import * as WebMidi from "webmidi"`, but then I get the following error:

```
Uncaught TypeError: Cannot read property 'WebMidi' of undefined
    at webmidi.min.js:31
    at webmidi.min.js:31
```

**Comment by djipco** [comment]
Unfortunately, I am not a TypeScript user and know very little about it. For that reason, WebMidi.js does not officially support TypeScript yet. I am looking to change that for version 3 but will need a knowledgeable TypeScript dev to work on the type definitions. 

At one point, users have reported that it was working (as you saw in issue #82) . I'm not sure why it isn't working for you. 

For personal bandwidth reasons, official TypeScript support will not come before version 3 (unless someone chimes in to help).

**Comment by michaelcaterisano** [comment]
Thanks @djipco. I did get the following syntax to work, which I found in the Tone.js/ui library:
```
const WebMidi: import("webmidi").WebMidi = require("webmidi");
```
A little funky, but it works!

**Comment by djipco** [comment]
@michaelcaterisano Thank you so much for taking the time to report back. It will probably be helpful to others. I added your technique to the [README](https://github.com/djipco/webmidi/blob/master/README.md#typescript-support).
