### ISSUE TITLE
website homepage forum link gives a 404

### ISSUE THREAD

**Issue by takyano** [djipco/webmidi#149]
**Describe the bug and how ro reproduce it**

Note Template typo in header above^^^
"ro" should be "to"

visit the webmidijs.org site.
click on the Forum link [Forum](https://webmidijs.org/forum) and get a 404 error.
note missing / at the end of the URL.
doing a page refresh will got to https://webmidijs.org/forum/

**Environment:**
Chrome Version 91.0.4472.101 (Official Build) (64-bit)
Windows 10

**Additional context**

**Comment by djipco** [comment]
This is odd. When the final `/` is excluded, the server correctly returns a `301 Moved Permanently` response which should trigger a new request from the browser, this time including the trailing `/`. This is what happens in my browser (Chrome on macOS) and the reason why I never saw the problem. I'm not sure why you are not getting the same behaviour.

Anyway, it's certainly better to add the final `/` and I thank you for taking the time to report this. Cheers!

P.S. I also fixed the typo in the template.
