### ISSUE TITLE
Way to play a frequency (hz) instead a note name? (for microtonal uses)

### ISSUE THREAD

**Issue by maximelebreton** [djipco/webmidi#151]
Hello @djipco, I can't find in the docs a method to play a frequency (hz) instead a note name, like `playFrequency('523.25')`, is there a way to do this?

Thanks!

**Comment by djipco** [comment]
@maximelebreton Synthesizing tones is outside the scope of WebMidi.js. If you need to play frequencies, have a look at the great [Tone.js](https://tonejs.github.io/) library.
