### ISSUE TITLE
output.stopNote("all") does not work as expected

### ISSUE THREAD

**Issue by joeljansonjohansen** [djipco/webmidi#163]
**Describe the bug and how to reproduce it**
Using this command does not stop any of the notes playing.
For example:

Starting a note with:
output.playNote("A3", 1);

And trying to end it with:
output.stopNote("all", 1, { time: "+2000" });

Does not work, however, this works:
output.stopNote("A3", 1, { time: "+2000" });

**Environment:**
Specify the environment where you are witnessing the problem:
Mac Big Sur
Chrome 93.0.4577.82
Webmidi - 2.5.3

**Comment by djipco** [comment]
> And trying to end it with:
> output.stopNote("all", 1, { time: "+2000" });

The first parameter of the `stopNote()` method is a note. The string `"all"` is not allowed in this context. However, maybe adding a `stopAllNotes()` would be a worthy addition to the library. I've added that to the list of [enhancements](https://webmidijs.org/docs/v2.5.3/classes/Output.html#method_stopNote) to evaluate.
