### ISSUE TITLE
Is midi.js dead? Are there alternatives?

### ISSUE THREAD

**Issue by agentcubes** [djipco/webmidi#166]
It appears that MIDI.js is not a very active repository. Last substantial updates are several years old. We are using MIDI.js as part of AgentCubes (a programming environment for kids). MIDI.js works ok in some browsers, e.g., Chrome, but is severely broken in others, e.g., Safari. Is MIDI.js essentially dead and if so, are there recommended alternatives?

**Comment by djipco** [comment]
I am transferring this issue to the "Discussions" section.
