### ISSUE TITLE
Make "Middle C" configurable/transposable

### ISSUE THREAD

**Issue by djipco** [djipco/webmidi#18]
The concept of "Middle C" in MIDI is a mess. Various manufacturers treat it differently, placing it at C3, C4 or C5. The MIDI standard does not address this. 

To make it easier to transition from one environment to another, WebMidi.js should allow the user to transpose MIDI note numbers to match what they require.

Here are some references on the subject:

- http://cote.cc/blog/logic-studio-9-midi-note-numbers
- http://www.pgmusic.com/forums/ubbthreads.php?ubb=showflat&Number=338513
- https://www.midikits.net/midi_analyser/midi_note_numbers_for_octaves.htm
- https://en.wikipedia.org/wiki/Scientific_pitch_notation

I'm scheduling this for a later release. **If you think it's worhwhile, give it a thumbs up**. This will give me an idea of how much people need it.

**Comment by antonioaguilar** [comment]
@cotejp Do you have an update the ETA for this feature? I'm writing a midi app that uses [VexFlow](https://github.com/0xfe/vexflow) and note mappings are coming all wrong. It would be great to be able to configure middle C mappings in WebMIDI. Thanks.

**Comment by cotejp** [comment]
@antonioaguilar This is scheduled for version 2.1 (April 1st). But first, I want to release version 2.0 in its final form.

**Comment by djipco** [comment]
This feature is currently in the `/src` version. A new setting called `WebMidi.octaveOffset` lets you globally offset octave numbering at will. 

_Note that the new version also makes middle C to be C4 by default. For the rationale behind this decision, see issue #42._

Before releasing it on NPM, I will be gathering feedback in issue #42. Your comments are welcome.

**Comment by djipco** [comment]
Available in [release 2.1](https://github.com/djipco/webmidi/releases/tag/2.1.0).
