### ISSUE TITLE
Some classes are not exported

### ISSUE THREAD

**Issue by galloween** [djipco/webmidi#204]
Hi! 
The lib seems to declare certain classes but not export them - for example, `Input`, `Output`, `InputChannel`, `OutputChannel`.
For now I have to manually edit the `d.ts` file (change `declare` to `export` for these classes).
Is there a right/different/better way to import those?

Thank you very much! Great work!

![CleanShot 2021-12-14 at 08 08 11](https://user-images.githubusercontent.com/2077754/145942649-118915ae-7247-432f-980a-52613604f691.png)

**Comment by djipco** [comment]
This is an easy fix but I'm not sure why you would need `Input` and `Output` to be exported. Is this something that TypeScript needs? As you can probably guess, I am not too familiar with TypeScript.

`Input`, `Output`, `InputChannel` and `OutputChannel` should not be instantiated directly. This is done by the library itself. Does TypeScript need them to be exported?

**Comment by galloween** [comment]
yes you are right, its a typescript thing and may be a bit confusing.

I was referring to the `d.ts` files, which is the types file, not the actual classes!

i guess the problem is, if the class itself is not exported, then the generated types are not exported as well...

so ideally, the `d.ts` file should have exports on everything,
but the classes themselves dont have to be exported.

for example, consider this,
here Im just marking the type of the variables so that i get all the code autocompletion and type checking:
```
let input: Input;
let output: Output;

input = WebMidi.inputs[0]; // OK
input = WebMidi.outputs[0]; // TYPE ERROR!
```

**Comment by djipco** [comment]
I just realized that the `@type` directives in the jsdoc (which is used to generate the TypeScript file) for `.inputs` and `.outputs` was set to `Array` instead of `Input[]` and `Output[]`. This is why the type was resolving to `any[]`.

I regenerated the TypeScript definition file. Can you try with the new one from the `dist` directory? If it work, I will publish a new version.

**Comment by galloween** [comment]
will do and update you!

**Comment by glend1** [comment]
npm isn't picking up the update yet. and i dunno how else to update the library.

**Comment by djipco** [comment]
I did not publish to NPM. You could just grab the definition file from GitHub.

**Comment by djipco** [comment]
Hold on. I have a fix for your other problem so I will publish to NPM in a second...

**Comment by galloween** [comment]
i manually copied the files from dist to node_modules webmidi folder.

the inputs/outputs types are fixed, like you said, but its still not possible to import types for related classes.

i can overcome it locally by taking it from the inputs/outputs, and use these for my needs:
```
export type WMInput = typeof WebMidi.inputs[0];
export type WMOutput = typeof WebMidi.outputs[0];
```
but maybe you would consider just exporting everything (both types and classes themselves) 😺 
there may be valid reasons to use the classes - for example to extend them to create something new etc.
you could mark them with `/** @internal do not use! */` or something like that.
but its already better, type-wise.

thanks!

**Comment by glend1** [comment]
still getting this error.

````
Module '"webmidi"' declares 'Input' locally, but it is not exported.ts(2459)
webmidi.cjs.d.ts(4351, 15): 'Input' is declared here.
````

**Comment by galloween** [comment]
☝️  yes, this.
 
(but now you can infer them from WebMidi inputs/outputs, save locally and use :) see above

**Comment by djipco** [comment]
Can you guys provide me with some sort of basic TypeScript examples with which I could test this?  I just need something that triggers the problem so I can test my fix.

**Comment by glend1** [comment]
import { WebMidi, Input } from 'webmidi';

**Comment by glend1** [comment]
I'm pretty new to Typescript myself but this doesn't throw any errors in my IDE. What are you doing?

    function request(input: WebMidi.MIDIAccess) {}

**Comment by djipco** [comment]
I fixed the issues with `Input` and `Output` by explicitly exporting all classes. However, TypeScript is now complaining about some of the native types. For instance, when the library creates an `Input` object, a `MIDIInput` object is passed to the constructor. TypeScript does not seem to know this object even though it is a [native object](https://developer.mozilla.org/en-US/docs/Web/API/MIDIInput). 

Am I expected to tell TypeScript that the parameter is of type `Any` instead of `MIDIInput`? Or perhaps there is a way to tell TypeScript that `MIDIInput` is a native object?

**Comment by glend1** [comment]
its working for me.

    function request(input: WebMidi.MIDIInput) {}

maybe it is a config thing. here is mine;

````{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true
  },
}
````

Not gonna lie, config for this kind of stuff is the worst, are you able to use other native objects?

**Comment by galloween** [comment]
not all dom api types are included in typescript, some need to be installed:
```
npm install --save @types/webmidi
```
this ☝️  one is requred by jzz, for example. ([npm](https://www.npmjs.com/package/@types/webmidi))

you should also add it to your lib `dependencies`!

**Comment by galloween** [comment]
@djipco Thanks for adding exports!!

About your MIDIInput, it seems you can not use `MIDIInput` type on its own, because its part of `WebMidi` namespace, so you have to use it as `WebMidi.MIDIInput`.
also (native) WebMidi types are not included by default in typescript,
and other libraries (JZZ for example) seem to require this package: `@types/webmidi` ([npm](https://www.npmjs.com/package/@types/webmidi), [source](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webmidi)).
hope this helps

<img src="https://user-images.githubusercontent.com/2077754/146513038-2f89ff2a-cb5d-4d33-81c7-6187df7e1753.png" width="500">

**Comment by djipco** [comment]
> About your MIDIInput, it seems you can not use MIDIInput type on its own, because its part of WebMidi namespace, so you have to use it as WebMidi.MIDIInput.
also (native) WebMidi types are not included by default in typescript,

Yes! This is exactly the problem. I expected all native objects to be known by TypeScript. I find it odd they are not. Anyway, this fixes the problem with all the classes from the Web MIDI API. 

I still have another one to fix before it all works. TypeScript still complain about the `Listener` class. I'm looking into it now.

**Comment by djipco** [comment]
Okay, I'm out of the rabbit hole (I think). Version 3.0.5, which is now available, should not cause the aforementioned problems with TypeScript. 

Can you guys test it and let me know how it goes on your side?

**Comment by glend1** [comment]
I will test it but I will need a few days.

**Comment by galloween** [comment]
After some quick test, did not have any problems! Seems good to me!! Thanks a lot! ❤️ 🎵

**Comment by djipco** [comment]
Awesome! I'm thankful that you took the time to report the issue and help me troubleshoot it.

**Comment by glend1** [comment]
Seems to work, but I am also looking for import WebMidiEventConnected and WebMidiEventDisconnected.

**Comment by djipco** [comment]
> I am also looking to import WebMidiEventConnected and WebMidiEventDisconnected

The `WebMidi` class does indeed trigger `"connected"` and `"disconnected"` events but there are no `WebMidiEventConnected` or `WebMidiEventDisconnected` classes. What are you trying to achieve? I'm not sure how I can help you with this.

> e Doesn't apprear to have any type associated with it.

When you use the `addListener()` method, you can add custom parameters to be passed to the callback (via `options.arguments`). This means that the callback can receive a variable number of parameters and those parameters can be of any type.

**Comment by djipco** [comment]
Since the originally reported problem seems to be fixed, I'm going to close this issue.

@glend1 Feel free to open a new issue regarding the `connected` and `disconnected` events or regarding `addListener()`. This will make it easier for me to track individual issues. Thank you.
