### ISSUE TITLE
remove input listeners not accessable on disconnected event

### ISSUE THREAD

**Issue by glend1** [djipco/webmidi#229]
my environment is next.js. when i attach the following listener;

````
WebMidi.addListener("disconnected", (e) => {
    e.port.removeListener()
})
````

i get this error `TypeError: e.port.removeListener is not a function`

i tried `e.target.removeListener()` i don't get the error, but i also don't think it removes the listener(s).

**Comment by glend1** [comment]
since 3.0.13 the error is now properly showing up with typescript.

````
This expression is not callable.
  Each member of the union type '(<T extends keyof InputEventMap>(type?: Symbol | T | undefined, listener?: InputEventMap[T] | undefined, options?: { channels?: number | number[] | undefined; context?: any; remaining?: number | undefined; } | undefined) => void) | (<T extends keyof OutputEventMap>(type?: Symbol | ... 1 more ... | undefined, listene...' has signatures, but none of those signatures are compatible with each other.
````

**Comment by djipco** [comment]
You should now (v3.0.14) be able to use `e.port.removeListener()` on `disconnected` events.

**Comment by glend1** [comment]
are you sure?

**Comment by djipco** [comment]
> are you sure?

Yes.

However, note that your code adds a listener to the `WebMidi` object and removes all listeners from the `Input` or `Output` that was disconnected. These are two completely separate things.

When you remove a listener, you need to remove it from the object where it was added. In this case, if you want to remove all listeners from `WebMidi`, you should use: `WebMidi.removeListener()`.

**Comment by glend1** [comment]
yep, sorry. your right. typescript is complaining about it though.

**Comment by djipco** [comment]
> typescript is complaining about it though.

Complaining about what? I don't seem to have a problem when I use it.

**Comment by glend1** [comment]
its telling me `This expression is not callable.`

**Comment by djipco** [comment]
I thought you meant the error was triggered by `WebMidi.removeListener()` when you actually mean the error is triggered by `e.port.removeListener()`. Sorry about the confusion. 

In all honesty, I have no clue why it reports an error. My (very limited) knowledge of TypeScript cannot decipher the error. I'm going to re-open the issue but we will have to find some knowledgeable TypeScript power-user to look into this.

Perhaps you could ask in the [Discussions](https://github.com/djipco/webmidi/discussions/categories/q-a) and reference this issue?

For the record, here is the generated error message:

```
TS2349: This expression is not callable.
Each member of the union type '(<T extends keyof InputEventMap>(type?: Symbol | T, listener?: InputEventMap[T], options?: { channels?: number | number[]; context?: any; remaining?: number; }) => void) | (<T extends keyof OutputEventMap>(type?: Symbol | T, listener?: OutputEventMap[T], options?: { ...; }) => void)' has signatures, but none of those signatures are compatible with each other.
```

**Comment by djipco** [comment]
I did some more digging today and I understand what the problem is. Basically, it goes like this: 

1. When the `disconnected` event is triggered by the `WebMidi` object, the callback function will be passed a `PortEvent`.
2. The `PortEvent` contains a `port` property which can either be an `Input` or an `Output` (either of which can be disconnected).
3. When you call `removeListener()` on this `PortEvent.port` object, the acceptable parameters are derived from either the `InputEventMap` type or the `OutputEventMap` type (depending which kind of port triggered the event). 
4. The problem is that `InputEventMap` and `OutputEventMap` do not have the same signature. This is what triggers the error.

So, to prevent the error, starting with v3.0.15, I am using a type of `any` for the `PortEvent.port` property instead of `Input | Output`. This is an ugly fix but I don't know how else this can be resolved since we cannot know ahead of time the type of port that triggered the `disconnected` event.

P.S. In v3.0.15, `OutputEventMap` is renamed `PortEventMap` since its properties are common to both input and output ports.

**Comment by glend1** [comment]
fair enough. If a solution arises will you make a note to fix it? or put a note somewhere that there is a limitation in the typescript implimentation?

Maybe it is an archiectural floor? Maybe connected inputs should be a different events to conntected outputs?

**Comment by djipco** [comment]
I have also started a [page](https://webmidijs.org/docs/going-further/typescript) with information regarding TypeScript. Hopefully this can act as a reminder of yet-to-solve problems.

**Comment by FractalHQ** [comment]
I can think of a few ways to sort this out -- is it still an issue?

**Comment by djipco** [comment]
The issue has been "fixed" with the aforementioned ugly workaround but if you have a cleaner solution, I'd love to hear it. Thanks for offering to help!

**Comment by dopry** [comment]
It sounds like the type of the port needs to be ['narrowed'](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#typeof-type-guards) to one of Input or Output so the event map is no longer ambiguous.

```typescript

import { WebMidi, Input, Output, PortEvent } from 'webmidi'

WebMidi.addListener('connected', (event: PortEvent) => {
      const port = event.port
      // port is either an Input or Output, therefore ambiguous.
      if (port instanceof Input) {
        // port is now Input and no longer Input | Output
      } else if (port instanceof Output) {
        // port is now Input and no longer Input | Output
      } else {
        // port is neither an Input or Output, strange things are afoot at the circle k.
      }
      // port is either an Input or Output, therefore ambiguous.
    })
```

**Comment by dopry** [comment]
Here is a fairly straightforward OO solution that should enable better polymorphism for Input and Output and will reduce quite a bit of duplicate code. 

```typescript
class Port extends EventEmitter { 
   // put all the common code from Input and Output here
   type: 'input' | 'output'
}
class Input extends Port {
  // things specific to Input
 type: 'input'
}
class Output extends Port {
  // things specific to output
  type: 'output'
}
```

This is how it's handled in the [browser implementation](https://developer.mozilla.org/en-US/docs/Web/API/MIDIOutput). It makes sense to parallel the class hierarchy. 

![Image](https://github.com/user-attachments/assets/14303e79-99bc-4685-9dab-12c46ab715d3)
