### ISSUE TITLE
Migration guide from 2.5.3 to 3.0.0?

### ISSUE THREAD

**Issue by josh83abc** [djipco/webmidi#245]
Hello guys,

I am the developer of a popular DJ webapp (https://you.dj).

I am using webmidi.js for a long time and I built a pretty complex MIDI module in my DJ app. Each time a new WebMidi.js version was released, I was simply overwriting the old version with the new version. It was always working UNTIL the version 3.0.0. I overwrite the 2.5.3 file with the 3.0.0 and I see strange things now. The MIDI control is not working in my app anymore. I assume you changed some things in the specifications. Can I have a list of changes you made?

Thanks!

**Comment by djipco** [comment]
I was actually working on a migration guide. Since you are asking, I am putting it online even though it's not quite finished as it may help you and others. 

The [guide](https://webmidijs.org/docs/migration/) is live now. Hope it helps.

**Comment by djipco** [comment]
By the way, if you feel like it, you can add your project to the [showcase](https://webmidijs.org/showcase) by modifying this page and submitting a PR: 

https://github.com/djipco/webmidi/blob/master/website/src/pages/showcase/index.md

Cheers!

**Comment by djipco** [comment]
Since I have not heard back, I will assume that you are satisfied with my answer and will close the issue. If you need, you can re-open it.
