### ISSUE TITLE
'WebMidi' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by maximedupre** [djipco/webmidi#247]
**Description**

There seems to be an issue with the typings 🤔

```
Error: node_modules/webmidi/dist/cjs/webmidi.cjs.d.ts:983:26 - error TS2702: 'WebMidi' only refers to a type, but is being used as a namespace here.

983   constructor(midiInput: WebMidi.MIDIInput);
                             ~~~~~~~


Error: node_modules/webmidi/dist/cjs/webmidi.cjs.d.ts:2199:27 - error TS2702: 'WebMidi' only refers to a type, but is being used as a namespace here.

2199   constructor(midiOutput: WebMidi.MIDIOutput);
                               ~~~~~~~


Error: node_modules/webmidi/dist/cjs/webmidi.cjs.d.ts:5385:14 - error TS2702: 'WebMidi' only refers to a type, but is being used as a namespace here.

5385   interface: WebMidi.MIDIAccess;
```

**Environment:**
Specify the environment where you are witnessing the problem:
  - Library version and flavour (CJS, ESM or IIFE): Not sure...seems like CJS?
  - Runtime (browser or Node.js) and version: Node v16.13.0
  - Language (JavaScript or TypeScript): TS
  - Operating system: macOS 12.2.1

**Comment by djipco** [comment]
I am not getting this error in an environment very similar to yours. Could you provide an example that triggers the issue? Perhaps it's something in your config file?

The `webmidi.d.ts` file depends on the basic types for the Web MIDI API (`MIDIInput` and `MIDIOutput`, for example) which are imported in the `package.json` file of WEBMIDI.js. Normally, you shouldn't have to worry about that but it's as though the `WebMidi` namespace from `@types/webmidi` is being confused with the `WebMidi` object defined in the library.

**Comment by maximedupre** [comment]
@djipco It seems like there is some sort of incompatibility with the angular build. I simply created a new angular project and imported WebMidi and the same error occurs.

Repo: https://github.com/maximedupre/web-midi-issue

Run `npm start`

**Comment by Vexcited** [comment]
I also have this problem with Vite + React. I use Node v17.3.0 and TypeScript on Linux (Pop!_OS).

The code from the project is also available here: https://github.com/Vexcited/lpadder/blob/main/src/pages/utilities/midi-checker.tsx

Here is the error I get when trying to build my project.
![image](https://user-images.githubusercontent.com/59152884/158029158-b761e11e-bd64-419e-9807-e39a64b2e989.png)

Hope it can help !

**Comment by djipco** [comment]
I will try to find some time to look at this this week. Unfortunately, I'm not a TypeScript developer so I feel out of my depth... We need to find a TypeScript expert that's also a WEBMIDI.js fan. Anyone?

**Comment by joshwilsonvu** [comment]
I'm not super familiar with library type declarations but it seems like you might need something like:

```ts
// get types somehow
import type { WebMidi, MIDIInput, MIDIOutput, MIDIAccess } from "...";

// export this type
export WebMidi;

// overlay with a namespace for accessing other types, 
// might be `declare namespace` instead
export namespace WebMidi {
  export MIDIInput;
  export MIDIOutput;
  export MIDIAccess;
}
```

**Comment by djipco** [comment]
@joshwilsonvu Thank you so much for your input. 

Here is something you probably should know to better understand the problem. By default, TypeScript does not know about the object types from the native Web MIDI API. So, I had to add [@types/webmidi](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webmidi/index.d.ts) as a dependency for the library. 

However, the namespace for the native objects (`WebMidi`) collides with the name of my main `WebMidi` object. I'm not sure what to do from there... Ideas?

**Comment by djipco** [comment]
Can I somehow rename the namespace of the imported types ([@types/webmidi](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webmidi/index.d.ts)) to, for example, `WebMidiApi` ? I could then use `WebMidiApi.MIDIOutput` without causing a conflict with my own `WebMidi` object.

**Comment by djipco** [comment]
Thanks to the feedback from @joshwilsonvu, I think I have finally found a solution. This is what I did:

1. Copy the type definitions for the native Web MIDI API into the head of `/typescript/webmidi.d.ts`;
2. Rename the native API's namespace from `WebMidi` to `WebMidiApi`;
3. Adjust all references to the namespace;
4. Re-compile the type definitions published to `/dist`;

With the new definitions, I was able to successfully compile the Angular example prepared by @maximedupre (thanks for that, by the way!).

@Vexcited Can you try it out and confirm that it works for you too? If it does, I will publish a new release. All you have to do is replace the following file in your project (`node_modules/webmidi/dist/cjs/webmidi.cjs.d.ts`) by [the matching one](https://github.com/djipco/webmidi/blob/master/dist/cjs/webmidi.cjs.d.ts) that is on GitHub.

**Comment by Vexcited** [comment]
Hello !

I've followed your instructions and it successfully built ! I can confirm that .cjs and .esm works on Vite + React.

**Comment by djipco** [comment]
Release v3.0.16 fixes this problem. Thanks all for your help!
