### ISSUE TITLE
Feature Request: please add support for React Native

### ISSUE THREAD

**Issue by elmcapp** [djipco/webmidi#250]
I have used the library in a React js project using the npm package. I like to known if there is current support with React Native. If not I would like to know if you could please provide support for React Native.

**Comment by djipco** [comment]
I have never tested the library in React Native, so you have more experience than I do on the matter. When you say you would like support for React Native, what do you mean exactly? Is there anything special that needs to be supported?

**Comment by elmcapp** [comment]
React Native macOS.   Basically React is a web app. React Native is native mobile app. React Native can run nodes js modules. It does not use browser view so the only way that I could use this I guest is with Node js backend however it will not work on React Native. I guess I have to figure this out.
