### ISSUE TITLE
Using WebMidi with Tauri Studio

### ISSUE THREAD

**Issue by elmcapp** [djipco/webmidi#251]
Tauri Studio allows us to develop software. Its an alternative to Electron web app  Tauri Studio allows use to make web based apps and I wanted to use it with WebMidi. Currently it works on windows computers however on Macs it does not work. Tauri Studio uses the native browser view of the computer system and WebMidi does not work in safari. That being  the issue my app is not working on Mac. Would WebMidi work with Rust, I have had success with Node js

**Comment by djipco** [comment]
Can you run Node.js modules in Tauri Studio ? If you can, this may be a path to a solution as WEBMIDI.js runs in Node.

**Comment by elmcapp** [comment]
Currently Tauri Studio backend is Rust. Support stated that we can SideCar Js modules.

Would you have any support for the Rust programming language.

**Comment by djipco** [comment]
I don't have much knowledge about Tauri Studio. WEBMIDI.js is a JavaScript library, and as such, offers no explicit support for Rust.

**Comment by elmcapp** [comment]
Tauri is web basic the problem is that it uses the native web view controller from the machine. So all of my Mac users can not use the software because of the issue with apple not supporting Web MIDI API. I now you stated that it will run on node js. It would be nice if Web Midi would bring support to Rust Programming language.

**Comment by djipco** [comment]
There are [several MIDI crates](https://crates.io/keywords/midi) for Rust already. I'm not sure what more I can bring to this environment.

**Comment by djipco** [comment]
As I stated, you can run WEBMIDI.js on Node.js on Mac. So, at least, there is a solution. Since there isn't much else I can do, I will close this issue. Feel free to reopen if needed.
