### ISSUE TITLE
webmidi on android/IOS ?

### ISSUE THREAD

**Issue by ryodes** [djipco/webmidi#294]
**Does webmidi work with android/IOS devices ?**

I am experiencing some troubles using your API on mobile devices. It works perfectly fine for desktop users but on mobile it seems that WebMIDI can not be enabled.

**Detail**

WebMidi.enable((error) => {
      if (error) {
        console.warn("WebMidi could not be enabled.");
        return;
      }
      console.log("WebMidi enabled.");
      if (WebMidi.inputs.length === 0) {
        console.log("No MIDI inputs.");
        return;
      }
      const input = WebMidi.inputs[0];
      input.addListener("noteon", "all", (event) => {
        this.handlePlayNoteInput(event.note.number);
      });
      input.addListener("noteoff", "all", (event) => {
        this.handleStopNoteInput(event.note.number);
      });
    });

here is my website with WebMidi:
https://learn-chords.netlify.app/

Thank you.

**Comment by djipco** [comment]
Are you getting the "**WebMidi could not be enabled.**" message? If so, which browser are you using and on which platform?

**Comment by ryodes** [comment]
I don't know what message I have on mobile, I can't open the element inspector, and for the browser, I'm using an android device with Chrome.

**Comment by ryodes** [comment]
ok i will try it, thanks

**Comment by ryodes** [comment]
oops, sorry, I totally forgot to answer.
yes i still have the problem on android.
When I connect my android device to my piano, I get the message "No MIDI inputs"

![image](https://user-images.githubusercontent.com/50877200/204309459-986974f0-301c-4996-8ce6-c4552093d134.png)

but it works fine on pc

**Comment by djipco** [comment]
Did you resolve this issue?

**Comment by ryodes** [comment]
no, but I have the impression that it's my piano which is not familiar with android webpacks, you can close this issue, I plan to make an application on mobile to test, thanks :)
