### ISSUE TITLE
Note duration ignored in channel.playNote

### ISSUE THREAD

**Issue by tobyhede** [djipco/webmidi#337]
When using playNote with a note containing a duration value, the duration is not used.

```
const note = new Note(value, { attack, duration })
channel.playNote(note);
```
I think I've tracked the issue to a Line 724 OutputChannel.js

The implementation of playNote accepts an options object and uses a duration value in this object:
https://github.com/djipco/webmidi/blob/fe5adbaed0e73025a8733e249ea059a02f371a08/src/OutputChannel.js#L724

**Comment by djipco** [comment]
This has been fixed in [release 3.1.4](https://github.com/djipco/webmidi/releases/tag/v3.1.4).
Thank you so much for reporting the problem.
