### ISSUE TITLE
playNote does not sendNoteOff when passed an array of notes.

### ISSUE THREAD

**Issue by tobyhede** [djipco/webmidi#344]
**Description**
When using `playNote` with an array of notes, duration is not handled correctly. 

Code currently assumes a single note, and does not check for or iterate through an array.

**Details**
The check for duration uses this line:
```
 if (parseInt(note.duration) > 0) {
```

**Comment by djipco** [comment]
Wow, it seems you are the first to realize this... Thanks for reporting and for the PR. I'll check it out as soon as I can.

**Comment by djipco** [comment]
Your PR, which fixes this issue, has been merged in. [Release 3.1.5](https://github.com/djipco/webmidi/releases/tag/v3.1.5) includes the fix. Thank you so much for contributing!
