### ISSUE TITLE
Accidental note names returned incorrectly in 

### ISSUE THREAD

**Issue by DataGreed** [djipco/webmidi#351]
**Description**
1. Follow the quickstart guide at https://webmidijs.org/docs/
2. Implement listening to MIDI events like this:
```
addListener("noteon", e => {
    document.body.innerHTML+= `${e.note.name} <br>`;
  });
```
3. Press F# on keyboard

** Expected result **

`F#` will appear on the page

** Actual result **

`F` appears on the page.

**Environment:**
Tested on mac in chrome with Korg Nanokey.

**Details**
Same happens with every accidental.

**Comment by tobyhede** [comment]
This confused me as well. 
The note has a separate accidental property. 

You should be able to use:
```
addListener("noteon", e => {
    document.body.innerHTML+= `${e.note.name}${e.note.accidental} <br>`;
  });
```

Might be worth adding a property that is the "full name" and includes octave, note and accidental.

**Comment by DataGreed** [comment]
Thanks!
