### ISSUE TITLE
There is no dist directory to grab the latest version from in the release archives

### ISSUE THREAD

**Issue by takyano** [djipco/webmidi#370]
**Description**
According to the docs:

https://webmidijs.org/docs/getting-started/installation#installing-manually

I should be able to download a copy of the latest release, webmidi-3.1.6.zip or webmidi-3.1.6.tar.gz and find the dist directory if I want a static copy of any of the build types, cjs, esm or iife.

Well it ain't there.

Does #253 have anything to do with this?

**Environment:**
  - webmidi-3.1.6.zip or webmidi-3.1.6.tar.gz

**Details**

**Comment by djipco** [comment]
Yes, this is definitely related to #253. I have updated the documentation to point to jsDelivr instead. Thanks again for reporting.
