### ISSUE TITLE
"Linking From CDN" on docs points to WebMidi.js v3.0.0-alpha.26

### ISSUE THREAD

**Issue by takyano** [djipco/webmidi#371]
**Description**
The docs:

https://webmidijs.org/docs/getting-started/installation#linking-from-cdn

point to a really old version of WebMidi 3.x

https://cdn.jsdelivr.net/npm/webmidi@next/dist/iife/webmidi.iife.js

```
WebMidi.js v3.0.0-alpha.26
A JavaScript library to kickstart your MIDI projects
https://webmidijs.org
Build generated on November 25th, 2021.
````

maybe @latest might be better.

**Comment by djipco** [comment]
Good catch! Thanks for reporting. The "@next" tag was used during the transition from v2 to v3 and I forgot to change it back. I updated it.
