### ISSUE TITLE
rawValue does not work for channelAfterTouch

### ISSUE THREAD

**Issue by woppa684** [djipco/webmidi#401]
As can be seen here, the value is always multiplied by 127

https://github.com/djipco/webmidi/blob/c8ab29cac632179f2e0f0d255c56b12d90ecaf16/src/OutputChannel.js#L1138C9-L1138C35

**Comment by djipco** [comment]
Thank you for reporting this. It has been fixed in [release 3.1.8](https://github.com/djipco/webmidi/releases/tag/v3.1.8) which is available on NPM right now.
