### ISSUE TITLE
Sendinf and receiving NRPN messages?

### ISSUE THREAD

**Issue by hems** [djipco/webmidi#41]
Is there a simple way of handling NRPN communication into the library ?

**Comment by djipco** [comment]
You should check out [`Output.setNonRegisteredParameter`](http://djipco.github.io/webmidi/latest/classes/Output.html#method_setNonRegisteredParameter).

**Comment by hems** [comment]
what about receiving NRPN?

**Comment by djipco** [comment]
There is currently nothing in WebMidi.js that automatically parses inbound NRPN messages. However, you are free to do your own parsing by listening to `controlchange` events. 

The tricky part is that to receive a single NRPNs, you actually have to parse several control change messages to select the parameter and then to assign it a value...

**Comment by hems** [comment]
@djipco that's okay, I already have a javascript algorithm which parses NRPN I just wanted to make sure I wasn't missing anything, I'll get on with this and hopefully make a PR with the NRPN parser soon.

**Comment by markidm** [comment]
@hems is there any movement on this? This is exactly what I'm looking for.

**Comment by hems** [comment]
@markidm unfortunately i didn't take this forward.

I got a gist with some of the code i was using to parse the NRPN messages, [in this gist](https://gist.github.com/hems/8246279cf28e8607fb0167da8b3deb9a) which is basically an adaptation of Cirs Hector's example code: http://tetradev.blogspot.com/2010/03/nrpns-part-2-nrpns-in-ableton-with-max.html

If you have any questions feel free to get in touch via email ( it's on my github profile ).
