### ISSUE TITLE
typescipt `ControlChangeMessageEvent` includes `{ channel: number }` which is actually undefined.

### ISSUE THREAD

**Issue by xinaesthete** [djipco/webmidi#427]
**Description**
This appears with auto-completion etc and can lead to writing something like `e.channel === channel` rather than `e.message.channel === channel`.

**Environment:**
`"webmidi": "^3.1.9"` as freshly installed via npm.
Browser ESM, Vite, TS, React etc.

**Comment by djipco** [comment]
Good catch! Thanks for reporting. Fixed in [release 3.1.10](https://github.com/djipco/webmidi/releases/tag/v3.1.10).
