### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by microcipcip** [djipco/webmidi#44]
Is it possible to support all browsers without installing Firefox/Chrome plugins? Would [jazz-soft/JZZ](https://github.com/jazz-soft/JZZ) play nice with webmidi?

**Comment by microcipcip** [comment]
@aik099 Isn't JZZ ment to be used as polyfill for browsers that don't support WebMIDI, or you still have to install a browser plugin for this? I tried JZZ on IE 11 and it doesn't work for me.

**Comment by aik099** [comment]
I have no idea. It would be faster to try that out.

**Comment by microcipcip** [comment]
Ok, thanks :)
