### ISSUE TITLE
Add musical instruments to play MIDI events

### ISSUE THREAD

**Issue by surikov** [djipco/webmidi#45]
You can add instruments to play MIDI events from keyboard, see
https://surikov.github.io/webaudiofont/examples/midikey.html

from .mid files, see
https://surikov.github.io/webaudiofont/examples/midiplayer.html

**Comment by djipco** [comment]
In the spirit of keeping the library lean and focused, I'd rather not add playback capabilities. After all, users who want to do that can easily combine both our libraries to do so. Most users use WebMidi.js for inter-device MIDI communication and do not need playback capabilities.
