### ISSUE TITLE
Incorrect type definitions for Input/Output properties state, connection, type

### ISSUE THREAD

**Issue by mikezaby** [djipco/webmidi#456]
Description
The Input and Output classes in the webmidi TypeScript definitions should use stricter types for certain properties to align with the Web MIDI API specification. Specifically:

state should be typed as MIDIPortDeviceState instead of string.
connection should be typed as MIDIPortConnectionState instead of string.
type should be typed as MIDIPortType instead of string.

This would ensure type safety and better developer experience when using webmidi in TypeScript projects.

Code Reference
The relevant definitions can be found here:
https://github.com/djipco/webmidi/blob/master/typescript/webmidi.d.ts#L4096

**Comment by djipco** [comment]
That's a good catch. Thanks for reporting.
Changes have been merged already and are available in version 3.1.12. 
Cheers!
