### ISSUE TITLE
Rescan devices

### ISSUE THREAD

**Issue by alearcy** [djipco/webmidi#48]
Hi! I would to update devices when they changed. To do this I followed this steps:

1) On Mac go to Audio/Midi setup and add, for examples, an IAC driver and a Network device.
2) At the startup of my app I started MIDI with `WebMidi.enable(e => etc...)` and I correctly have 2 inputs and 2 outputs (Network and IAC)
3) Go to Audio/Midi setup and delete one MIDI device (ex: Network device)
4) In my app I fired a function that stop and re-start WebMidi with  `WebMidi.disable(); WebMidi.enable(e => etc...);`
5) I always got two devices instead of one.

EXPECTED: When I stop and re-start WebMidi I expected to have the update devices list.

I'm doing wrong?

Thanks! :-)

**Comment by aik099** [comment]
Yes, you're doing everything correctly. According to code disabling and enabling should requery all inputs/outputs. I'm suspecting that Web Browser process (e.g. `chrome.exe`) is actually caching MIDI devices inside it and never monitors if they've changed externally.

Does reloading the web page with your app show new MIDI devices?

**Comment by alearcy** [comment]
Thanks for your reply @aik099 
I'm developing an Electron app. A simple webview refresh doesn't solve the problem. Actually, I have to stop and relaunch the app to view the refreshed devices lit :-(

**Comment by djipco** [comment]
There hasn't been any response to the suggestions made by @aik099, so I'm going to close this issue. If you ever need more help on the matter, do not hesitate to reopen the issue.
