### ISSUE TITLE
Provide a default export to load the module via ES6 imports

### ISSUE THREAD

**Issue by TimPietrusky** [djipco/webmidi#49]
In order to load the module using ES6 imports and without a bundler like webpack, it would be nice to provide a `export default`, so WebMidi.js can be loaded like this:

```js
import WebMidi from '/node_modules/webmidi/webmidi.min.js'
```

## What happens instead
The following error is thrown:

```
Uncaught (in promise) SyntaxError: The requested module '/node_modules/webmidi/webmidi.min.js' does not provide an export named 'default'
```

**Comment by djipco** [comment]
@TimPietrusky Do you have pointers as to how I could do this quickly and painlessly? I'm aiming to convert version 3 to ES6 and, obviously, provide a default export (as well as various other goodies). 

However, this will only come when I have more time than I do currently. Until then, do you see a simple way to satisfy your request?

The library is currently using this (old-fashioned) approach:

```javascript
  if ( typeof define === "function" && typeof define.amd === "object") {
    define([], function () {
      return wm;
    });
  } else if (typeof module !== "undefined" && module.exports) {
    module.exports = wm;
  } else {
    if (!scope.WebMidi) { scope.WebMidi = wm; }
  }
```

**Comment by djipco** [comment]
I'm closing this but I added a reference to it in the [Enhancements](https://github.com/djipco/webmidi/wiki#enhancements) section of the wiki.

**Comment by TimSusa** [comment]
My guess would be: ```  export default from ''./path-to-webmidi.min.js" ``` put in an index.js would do the job, but I keep on my standpoint to prefer named exports. As a matter of fact they are much more explicit and help more as default exports. Please consider, that for export default you do not have to give a name at all for what you are exporting. If some contributor for example is importing some of your component in your code, it is not clarified, how he will name this thing and this is bad for code style and readability.

**Comment by djipco** [comment]
Yep. I totally agree and will definitely use a named export and default in v3.
