### ISSUE TITLE
Export TS interfaces so they can be used for compile-time type checking

### ISSUE THREAD

**Issue by spencerudnick** [djipco/webmidi#54]
Hello, lovely library! Thanks for all the work on this.

I'm working on a general timing library for Web Audio / Web MIDI applications, and would like to have intellisense and type checking for Interfaces that make up the `webmidi` package.

As an example, I can say `const input = webmidi.inputs[0]`. TypeScript indicates that `input` is of type `Input`, but I cannot write functions which accept the `Input` type as a parameter, and have to either manually copy the `webmidi.d.ts` to my source directory, or use the `any` type annotation.

I'm happy to submit a pull request if this is not a current priority!

**Comment by djipco** [comment]
I do not use TypeScript, so I'm not too familiar with it. If you submit a PR, I will happily merge it. The original `webmidi.d.ts` file has been graciously contributed by @mmmveggies 



If you submit a pull request, perhaps you could coordinate

**Comment by djipco** [comment]
PR [#55](https://github.com/djipco/webmidi/pull/55) has been merged to address this. Thank you!
