### ISSUE TITLE
bank select korg x50

### ISSUE THREAD

**Issue by zapex2018** [djipco/webmidi#57]
First of all, congratulations for your work !!
I am a musician and passionate about programming.
I'm trying to control a korg x50.
I managed to change instrument (with program change) but I can't change the sound bank (bank select) is it possible?

Thanks in advance Enrico

**Comment by jpw** [comment]
I am not an author of the project, but I hope this helps:

- Bank Select is done via MIDI CC's (Control Change messages)
- MIDI CCs `0` and `32` are assigned to Bank Select functions.
- You can use [sendControlChange](http://djipco.github.io/webmidi/latest/classes/Output.html#method_sendControlChange) to send CC's.
- What _values_ to send will I think depend on the MIDI implementation of your synth, which should be in its manual.

I hope that's enough info to help you with your issue, good luck 😄

**Comment by djipco** [comment]
@jpw is right. If you need more than 128 programs, bank selection is a little bit trickier as it involves sending two MIDI messages: one for the MSB and one for the LSB. That is why, in the [documentation](http://djipco.github.io/webmidi/latest/classes/Output.html#method_sendControlChange), you will see both **bankselectcoarse** and **bankselectfine**. You can get more info here: 

- http://midi.teragonaudio.com/tech/midispec/bank.htm
- https://www.midi.org/specifications/item/table-3-control-change-messages-data-bytes-2

I'm going to tag this as an **enhancement** because it would be nice if the library handled this automatically. I'm not sure how but I'll keep it here as a reference.

**Comment by zapex2018** [comment]
I thank you for the suggestion but could I have an example?
My keyboard shows: Bank Select function 0.32 MSB LSB

I'm trying..
output.sendControlChange (0, 0, 1);
output.sendControlChange (32, 2, 1);

but nothing from ..please help me ... thanks Enrico

![dat](https://user-images.githubusercontent.com/44204934/54965869-a84d1200-4f72-11e9-9dec-b5622ec8cd3b.jpg)

**Comment by djipco** [comment]
Your code looks good. However, the documentation you provided doesn't say which values are supported. So you might want to try other value combinations (or look elsewhere in the doc for supported values).

By the way, while testing your example, I realized there was a small bug when using string names for the controllers. Version 2.3.3 fixes that issue. If you download it, you will be able to simply use controller names like so:

```javascript
 WebMidi.outputs[0].sendControlChange("bankselectcoarse", 12);
 WebMidi.outputs[0].sendControlChange("bankselectfine", 34);
```

**Comment by zapex2018** [comment]
Thanks problem solved! I write scripts and Korg X50 bank select data with example.
Thanks again for the valuable help!

`<script type="text/javascript">
WebMidi.enable(function (err) { 

if (err) {
console.log("WebMidi could not be enabled.", err);
} else {
console.log("WebMidi enabled!");
console.log(WebMidi.inputs);
console.log(WebMidi.outputs);
var output = WebMidi.outputs[0];
var outputname = "USB Uno MIDI Interface [0]";
WebMidi.outputs[0].sendControlChange(0, 63);  // bank B
WebMidi.outputs[0].sendControlChange(32, 1);  // bank B
output.sendProgramChange(121, 1, 1); //
} 
});
</script>`

![bank_select_korg_x50](https://user-images.githubusercontent.com/44204934/55013246-074d6e00-4fe9-11e9-9e90-1aba6390008d.jpg)

**Comment by djipco** [comment]
Ok, awesome!

**Comment by djipco** [comment]
I'm closing this but I added a reference to it in the [Enhancements](https://github.com/djipco/webmidi/wiki#enhancements) section of the wiki.

**Comment by djipco** [comment]
Version 3.0.0-alpha.16 now includes the ability to specify both MSB and LSB at once (for controllers 0 to 31) by passing a two-value array as the second parameter:

```javascript
sendControlChange("bankselectcoarse", [12, 34]);
```
The line above results in two control change messages being sent: one for **bankselectcoarse** (0) with an MSB value of 12 and another one for **bankselectfine** (32) with an LSB value of 34.
