### ISSUE TITLE
toMidiChannels() should be able to return empty array by parameter 'none'

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#58]
Hey, 

I would like to create a PR, but I am not allowed to push to your branch.

At the moment the 'toMidiChannels()'  function returns full set of midi-channels for undefined input, which is ok. 

I would like to request a feature. It would be nice to have the 'toMidiChannels()' returning an empty array by giving in parameter 'none' with type string. In that manner, it would be possible to chose empty selections for UI-Menus in a more simple way.

``` 
  WebMidi.prototype.toMIDIChannels = function(channel) {

    var channels;

    if (channel === 'all' || channel === undefined) {
      channels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16];
    } else if (channel === 'none') {
      channels = [];
    } else if (!Array.isArray(channel)) {
      channels = [channel];
    } else {
      channels = channel;
    }

    // You could save that line, see above
    //if (channels.indexOf('all') > -1) {
    //  channels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16];
    //}

    return channels
      .map(function(ch) {
        return parseInt(ch);
      })
      .filter(function(ch) {
        return (ch >= 1 && ch <= 16)
      });

  };

```

**Comment by djipco** [comment]
I think that's a fine idea. It just adds flexibility. You can submit a PR and I'll merge it in. Do not forget to document it.

**Comment by TimSusa** [comment]
Hey, I have prepared a PR which is on a local branch. Would you please add me as contributor or give me more rights? ATM I am not allowed to push a branch to your repo.

**Comment by djipco** [comment]
You can't push but you should be able to make a pull request, no?

**Comment by TimSusa** [comment]
...from which branch should I do that?

**Comment by djipco** [comment]
You can do it straight to master.

**Comment by TimSusa** [comment]
OK, so I should fork you project... is that really necessary?

**Comment by djipco** [comment]
That's usually how it's done, isn't it? In any case, that's how contributors have done it thus far and how I've contributed to other projects as well.

**Comment by TimSusa** [comment]
No Probs from my side...

**Comment by TimSusa** [comment]
I would like to offer: https://github.com/djipco/webmidi/pull/62

**Comment by djipco** [comment]
Your PR (#62) has been merged. 
Thanks!
