### ISSUE TITLE
Test-Environment is missed

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#59]
Hey, 

I cloned your project and did try to run tests. Then I noticed, no test is really connected to any script in package.json. A lot of stuff is missed, like package entries for sinon, .. in  package.json. Furtheremore, a whole test-chain is missed.

Is there any way, that you could provide a way to test your framework for contributors?

**Comment by djipco** [comment]
Yeah, I know. Tests are in a messy state right now. You can view the results of the tests by opening the `index.html` page inside the `test` folder. This is also something I will need to sort for v3.
