### ISSUE TITLE
Drop Support for bower

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#60]
Hey, just be modern! 

Support for bower is not really needed anymore, in my opinion. Everything can be done due to npm with yarn now.

**Comment by djipco** [comment]
That's a good suggestion which will probably happen with v3. However, it doesn't hurt anyone if it remains there for a while...

This suggestion has been moved to the wiki's [enhancements section](https://github.com/djipco/webmidi/wiki#enhancements).
