### ISSUE TITLE
Drop support for Grunt and convert to parcel, rollup or webpack

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#61]
Drop support for Grunt and convert to parcel, rollup or webpack. You will achieve the same with less code. 

For Example parcel would provide you with a full library-release with: 

```
parcel build ./src/index.js
```

**Comment by djipco** [comment]
That's an excellent suggestion which will probably happen with v3. In the meantime, I moved your suggestion to the [wiki's enhancement](https://github.com/djipco/webmidi/wiki/Home/_edit#enhancements) section.

**Comment by jpw** [comment]
Just as a cautionary note, here's a few things I take in to account when thinking about updating tooling;

1. how well supported are the alternatives?
1. how often does it introduce breaking API changes? (looking at you, webpack)
1. how many dependencies does it have? when managing chains of NPM dependencies, one semver mistake or abandoned package anywhere in the chain can lead to vulnerabilities and other problems that are hard to patch
1. how opinionated is it? do we agree with those opinions?

Less code usually means hidden complexity.
