### ISSUE TITLE
[TEST] Files, containing tests should get filename-postfix *.spec.js or *.test.js

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#63]
In order to build up a test environment it is some kind of tradeoff to name files containing tests with postfix *.spec.js or *.test.js.

In that manner a test-runner could collect test-files more easy from a given root-folder, even if tests are located in deep nested folder structures without any extra configuration.

**Comment by djipco** [comment]
Since all tests are under the `/test` directory, I don't see a real need for this. Some people mix the production and test files in the same directory but I find this a bit messy.

**Comment by djipco** [comment]
In the end, for reference, test files are using `.test.js`.
