### ISSUE TITLE
[TEST] test libs WebMIDIAPI could be renamed to WebMIDIAPIShim

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#64]
It was some kind confusing to me, because I thought an old version of webmidi-api was used there. But actually it is a shim.

**Comment by djipco** [comment]
Yes, this makes total sense. Can you make a PR? 
P.S. Don't forget to change it in `index.html`

**Comment by TimSusa** [comment]
I can offer https://github.com/djipco/webmidi/pull/67

**Comment by djipco** [comment]
Merged.
