### ISSUE TITLE
Establish Mono-Repository

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#65]
In order to support and offer a backwards compatible version beneath a modern-version of webmidi I would suggest making use of a mono-repository via lerna optionally with yarn workspaces. Root point could be a folder called packages, where different webmidi deployments / versions could live in. In that manner we could establish supporting the classic and the modern world, maybe using a common core component. Furthermore, comparisons for different build tools / transpilers could be tested in different package subfolders.

**Comment by djipco** [comment]
Hmm... That's something to think about. However, I like to keep things simple. What I had in mind was for v3 to be the "modern" version while keeping v2 available for a long time.

**Comment by TimSusa** [comment]
Yes, that is exactly, what I am talking about. With lerna import, you could import any repository with all git history information. All the structure of the repo is retained, just only in a subfolder of "packages". You would be able to do full versioning and publishing of the modern and the classic version or even booth. You could even say, you have a basic version of something in your root and package subfolders are consumed by that something or the other way around.

**Comment by TimSusa** [comment]
@djipco I can offer you to create a monorepo as mentioned with lerna and yarn workspaces with two packages. First package is the old untouched version. Second package could pose the starting point for the modern version. Please let me know, if you are interested.

**Comment by djipco** [comment]
@TimSusa In all honesty, I do not know anything about monorepo, lerna or yarn workspaces. Before moving forward with this, I will have to educate myself. Also, I do not want things to get unnecessarily complicated.

**Comment by TimSusa** [comment]
@djipco No problem. This should only pose an offer. I will close this issue.
