### ISSUE TITLE
[TEST] Establish E2E Test

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#66]
In order to fulfil the test-pyramid, an e2e test could be established via cypress or puppeteer that simply runs existing index.html from test folder. Furthermore, all the selectors (testing midi stuff) could be checked for being ok and console output could be tracked. Circle CI could be used for free for test-automation and connecting the results to all github pull-requests.

This issue is connected to https://github.com/djipco/webmidi/issues/63

**Comment by djipco** [comment]
The problem with testing this lib is that we need to have MIDI devices plugged in to get relevant results. Without a device plugged in, there's only so much we can test.

**Comment by jazz-soft** [comment]
FYI, you can emulate MIDI devices using https://github.com/jazz-soft/midi-test

**Comment by djipco** [comment]
Yeah, that's a good tip. Maybe it could be used during testing.

**Comment by TimSusa** [comment]
Sounds and looks quite good. @jazz-soft: Thanks for that input. I will give it a shot

**Comment by djipco** [comment]
If we could use that to conduct tests with virtual MIDI devices (I/O), that would be a real step forward.

**Comment by TimSusa** [comment]
OK, for so far I ran into a couple of problems, finding no solution atm:

- I took your example test from here: https://github.com/jazz-soft/midi-test/blob/master/test/mocha.js, installed everything, run that test, no big deal

- I tried to bind web-midi-lib into the test, where I was forced to mock
 navigator.requestMidiAccess. I try to use generator functions, which should take info from this.info() stemming from your jzz library. The problem, is that no driver-information could be observed in webmidi, which disables its workings and enable() function is not called.
 Maybe somebody could help here?

``` 
var assert = require('assert');
var mt = require('midi-test');
var JZZ = require('jzz');

describe('MIDI messages', function() {
  it('jzz', function(done) {
    JZZ().and(function() {
      console.log(this.info());
      done();
    });
  });
  it('virtual-midi-in', function(done) {
    var port = mt.MidiSrc('Virtual MIDI-In');
    port.connect();
    JZZ().refresh().and(function() {
      console.log(this.info());

      const arr = this.info().inputs.map(item=>{
        return {...item, open: ()=> {return item}}
      })
     function* gen() {
        yield* arr;
      }

      navigator = {
        requestMIDIAccess: ({sysex}) => {
          return new Promise((res,rej) => {
            res({
              inputs: {
                values: gen
              }
            })
          })
        }
      }
      let webmidi = require('../src/webmidi')
      webmidi.enable(err => {
        if (err) throw new Error(err)
        console.log('It refuses to land here!');
        done();
      })
      // port.disconnect();
      // done();
    });
  });
}); 
``` 

- When step-debugging through the test, it claims: 

```  
Destroying MacOS CSrc
dyld: lazy symbol binding failed: Symbol not found: _napi_create_threadsafe_function
  Referenced from: /Users/timsusa/data/development/webmidi/node_modules/midi-test/build/Release/miditest.node
  Expected in: flat namespace

dyld: Symbol not found: _napi_create_threadsafe_function
  Referenced from: /Users/timsusa/data/development/webmidi/node_modules/midi-test/build/Release/miditest.node
  Expected in: flat namespace
``` 

- @jazz-soft I even tried to dig through all your libraries and  I tried to understand code from https://github.com/jazz-soft/JZZ/blob/master/javascript/JZZ.js but it is not that easy to get an overview here in that limited amount of time, that I have. Do you have some tips for mocking out navigator.requestMidiAccess with your midi-test lib information?

- @djipco In my opinion, it seems somewhat problematic, directly relying on navigator.requestMidiAccess in a node.js environment. Maybe it could make sense to offer an interface, which could be injected to webmidi from the outside for testing purposes or non-browser environments (or is it already there as this.interface?). 

- another idea, which I had, would be taking your existing index.html and find a way to build up a test with jsdom similar to here: https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md#using-enzyme-with-jsdom. Anyhow, I did not try this.

**Comment by TimSusa** [comment]
Hey, I have succeeded to convert all your tests. Furthermore a visual midi driver test was created. Stuff runs on my mac without the need of a browser. All 94 Tests are passing. I would appreciate your feedback. https://github.com/djipco/webmidi/pull/74/commits

**Comment by djipco** [comment]
Tests are passing on my side too (macOS also). I think that's a good base to start with. Thanks a lot!

**Comment by TimSusa** [comment]
@jazz-soft big big thanks for your input. I wonder, if you would pose this library for production purposes. I mean I would have the need to create virtual midi ports out of my private application
