### ISSUE TITLE
[TEST] Concept for dividing up into unit-tests

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#70]
- At first, all functions, which do not use webmidi-api directly, could be separated. Those functions can be easily tested by mocking out inputs and outputs (I know, that is a lot of work, but maybe there are ways to reuse stuff)

- For all functions, which use webmidi-api directly, another mock could be established. I have good experiences using jest mock: https://jestjs.io/docs/en/mock-functions, you even can create a global mock, where you can mock out any node-module from the outside: https://jestjs.io/docs/en/jest-object#mock-modules

All this would need some further investigation, but I think it could pose a way to get test-coverage for all your sources, without using any browser. Furthermore, you could then easily automate tests and track, if any breaking changes were introduced.

**Comment by djipco** [comment]
That's an interesting approach. However, I see 2 drawbacks:

1. It seems like a lot of work to mock everything;
2. If a browser changes its implementation of the Web MIDI API, we won't know if it breaks something. Since the Web MIDI API is still new (not even released in Firefox yet), this is likely to happen.

**Comment by TimSusa** [comment]
As it turns out to me, navigator.requestMidiAccess(..., ..) is the main actor in the movie. I played arround a little bit with iterables and generators, where I found: 

``` 
function* gen() {
  yield* ['a', 'b', 'c'];
}

gen().next(); // { value: "a", done: false }
```

Imagine, the abc-array is just a midi input array, so I succeeded to mock out for so far, that your webmidi lib was at least in a state, where some stuff could be tested.

```
navigator = {
   requestMidiAccess: ({sysex: true}) => new Promise((resolve, reject) => {
    resolve({
      inputs: gen
    })
})
} 
```

... in that matter somehow...

**Comment by TimSusa** [comment]
... I don´t like open issues. As a matter of fact I will close this issue.
