### ISSUE TITLE
Establish linting and code formatting

### ISSUE THREAD

**Issue by TimSusa** [djipco/webmidi#71]
Hey, 

sry for all that issues, but to be honest, I could actually see there is no linting or code-formatting at all. For my projects eslint and prettier did the best the job. You can easily chose between plugins and chose a basic setup of settings configured via so called .eslintrc. The linting can easily be started in package.json and included to the test script. I would suggest that for the new version.

https://eslint.org/
https://prettier.io/
https://github.com/prettier/prettier-eslint
https://prettier.io/docs/en/integrating-with-linters.html
https://github.com/mysticatea/eslint-plugin-node

**Comment by djipco** [comment]
Actually, ESLint is configured in my editor but since I have been the only one working on this project, I never saw the need to include it in package.json.

What do you suggest?

**Comment by TimSusa** [comment]
Hey, 

You already have a couple of stars and contributors. In my opinion, It would be good to have a common eslint configuration available as ".eslintrc.js" as well as ".prettierrc" in the root folder. I experienced contributors, which had their own IDE code-formatting-settings enabled or linting stuff, which ended up in huge code-changes, where maybe only one line was doing something really important at the end. Furthermore, the other contributor anew had his own IDE settings, which ended up in... 

Maybe a basic configuration would be enough.

**Comment by djipco** [comment]
Makes total sense. I committed my `eslintrc.js` file. We can use that as a starting point. I have not used **prettier**, though. Do you feels this is necessary?

We probably should  also add a `lint` script to `package.json`. WebStorm takes care of that for me so I never bothered...

**Comment by djipco** [comment]
I added a `lint` script to `package.json`.

I checked out **prettier**. It's pretty cool but there is one thing that bothers me. It does not allow [padded blocks](https://github.com/prettier/prettier/issues/2352). I think this makes the code much harder to read. Let's stick to **eslint**  for now. If the need arises, we can always set up **prettier** later. 

P.S. Keep the suggestions coming. This keeps me on my toes!
