### ISSUE TITLE
14-bit support

### ISSUE THREAD

**Issue by PusherLabs** [djipco/webmidi#72]
Are there any plans for explicit 14-bit support?

**Comment by djipco** [comment]
Do you have anything specific in mind? Are you talking about RPNs and NRPNs? Or perhpaps CCs ?

**Comment by djipco** [comment]
It's been a week and I have not received any feedback so I'm going to close this for now. You can always reopen it with more details if you feel like it.

**Comment by TimSusa** [comment]
Hey, 

@PusherLabs: I just want to kindly ask, what kind of explicit 14-bit support you want? I mean it is a very interesting question, but lacks of more input. 

Clarifying things?

http://www.midiox.com/cgi-bin/yabb/YaBB.pl?board=Mapping;action=display;num=1410436593

**Comment by misterinterrupt** [comment]
from what I understand, 14-bit support is rpn/nrpn send and receive
