### ISSUE TITLE
Array of notes and velocity / duration ?

### ISSUE THREAD

**Issue by benoitmercusot** [djipco/webmidi#75]
Hi, 

I'm starting to work on a small project with your lib and I think it's awesome :)
But i'm currently stuck on something i'm trying to achieve... i would like to send an array of notes on channel 10 (ie drum channel) to trigger a kick and a snare (for instance). I can do that with the playNote method but i can't find a way to send different duration / velolicty for each note of the array (ie i want the kick @100 and the snare @50). What do you think ?

Thanks,

Benoit

**Comment by djipco** [comment]
As it is now, `playNote()` uses the same duration for all notes (meant for chords). To achieve what you want, you will have to call `playNote()` several times in a row with different durations. 

Since this is a good idea, I am adding this feature request to the [wiki](https://github.com/djipco/webmidi/wiki)'s enhancements section. 

Thanks for your input.

**Comment by benoitmercusot** [comment]
Thanks for the very fast reply and the enhancements proposition :)
I'm currently working with the multiple playNote() you're mentioning and i have few sync / time issues.  (ie kick and clap not perfectly synchronised) but i think it's caused by cpu (make sense since instruction are not synchrone) 
Keep up the good work !
Benoit.

**Comment by djipco** [comment]
@benoitmercusot The syncing issues are strange. At the MIDI level all notes are always sent sequentially, one after the other even for notes that are supposed to be played at the same time. It goes out so fast that we don't hear any delay. 

There might be something else at play here...

**Comment by benoitmercusot** [comment]
@djipco thanks for the feedback. i actually worked a bit on my side. Since i'm quite new to this i read and tried a lot of things this last coupled of days. And i figured out my main issue was that there's is no proper way to loop faster & accurately enough with javascript to simulate a midi clock. Window.requestAnimationFrame() is cool but it's 60fps so perfect for 150 bpm clock (@24ppq 16ms interval) but when you are trying different tempo all you have is workaround ! (ie 120bpm is 20.8ms for 24ppq). SO, i turned the problem the other way and i managed to slave my sequencer to Logic thourgh "IAC driver" and now i have a perfectly synchronised script (listener on clock). And from there my 16 step sequencer move every 6 event. 👍 (well my mac heat up a bit ...) 

Finaly you are perfectly right, there's no "perfectly synchronise" chord or battery part in MIDI. So i'm sorry for the confusion. But thanks to you to project is going well. Today i found this, and it's awesome to : https://github.com/g200kg/webaudio-controls

**Comment by djipco** [comment]
Ok, excellent!

By the way, you could probably have used the WebAudio clock to do the synchronization: https://sonoport.github.io/web-audio-clock.html

Cheers!

**Comment by benoitmercusot** [comment]
Yeah, i have been through there to !
But you always end up relying on either setinterval or requestAnimationFrame. I don't think the webaudio clocks emits event by itself

**Comment by djipco** [comment]
I have not tried it myself but I believe you can:
https://www.html5rocks.com/en/tutorials/audio/scheduling/

Cheers!

**Comment by benoitmercusot** [comment]
Absolutely right if you are dealing with pure audio or midi send event without a clock involved !
My 16 steps sequencer has for instance 125ms interval between steps @120 bpm with 4 note per quarter. But a midi clock is 6 time faster. Well i don't say it's impossible but i failed :( 

At the end my sequencer will have to be slave so incoming clock was fixing two problems !

**Comment by benoitmercusot** [comment]
Just FYI this one actually works actually great. combining setTimeout(fn,0) and audiocontext timer !
http://alexkort.com/midiseq/
