### ISSUE TITLE
SendSongPosition accurate ?

### ISSUE THREAD

**Issue by benoitmercusot** [djipco/webmidi#83]
Hi !
I have weird issues with Ableton Live.
When i'm sending only clock message with your lib everything is fine regarding the tempo/bpm.
But when it comes ton song position everything goes upside down.... like the song si moving WAAAY to fast ... currently i'm sending and INT every 6th clock. I think that is a good approach.

Anything on your side regarding the SendSongPosition function / implementation ?

**Comment by TimSusa** [comment]
Hey, 

from my side I try to understand your problem, but it lacks of information (we are not an official supporter of proprietary Ableton Live by the way). 

1. Can you describe the problem in more detail? What do you want to achieve?
2. What Operating System are you using?
3. Can you describe your setup more in detail (maybe with a screenshot)?

Thanks in advance, 

Tim Susa

**Comment by benoitmercusot** [comment]
Hi TimSusa, thanks for your reply. After digging a bit i found i made a mistake. Song Position is not something i need to send continuously; but only on play, start, stop and continue.everything works as excpected now !
