### ISSUE TITLE
Query CC values?

### ISSUE THREAD

**Issue by ONE75** [djipco/webmidi#84]
First of all, thank you for your work! I've been playing with webmidi for an hour and I have a working ReactJS prototype. Awesome!

One of the things I would like to do is query the current values of the parameters in the synth I'm using (Novation Circuit). For example, CC 80 is mapped to a rotary knob on the device. I want to query the current value of CC80 so I know at what position that knob is.

Many of the editors I know 'jump' to a position when the value changes (by using an eventhandler) so I'm not sure it's supported in the protocol?

As an alternative I can query the current patch with sysex but that requires extra parsing and I'm not interested in all the values.

Any feedback highly appreciated!

Thanks again,
Stijn

**Comment by djipco** [comment]
Stijn,

Thanks for your nice feedback.

The ability to query a controller is not built into the MIDI protocol which is (mostly) unidirectional. Actually, this will probably be included in MIDI-CI (a.k.a. MIDI 2.0). As far as I know, the only way to do it is to use sysex and manufacturer-specific code.

Cheers!

**Comment by djipco** [comment]
Since I haven't heard back from you, I'm going to close this. Feel free to reopen if you ever need.
