### ISSUE TITLE
Is webmidi can send runnnig status?

### ISSUE THREAD

**Issue by tatsuya-takahashi** [djipco/webmidi#85]
Web midi api can't send running status.
https://github.com/WebAudio/web-midi-api/issues/24

So is webmidi can send runnnig status?
If webmidi can send running status, Dosen't webmidi send midi via web midi api?

**Comment by djipco** [comment]
The WebMidi.js library is a layer added on top of the Web MIDI API. The Web MIDI API spec [explicitely says](https://www.w3.org/TR/webmidi/#widl-MIDIOutput-send-void-sequence-octet--data-double-timestamp) the following regarding the `send()` method:

> Running status is not allowed in the data, as underlying systems may not support it.

This means WebMidi.js **cannot** send _running status_ messages. This is true for inbound messages as well. Chris Wilson provides a clear [explanation](https://github.com/WebAudio/web-midi-api/issues/24#issuecomment-42204401) for this.

It could be possible for WebMidi.js to fake _running status_ in its own API while sending separate messages upstream. However, unless there is a clear need for this from the community, I do not see us going in this direction.

Cheers!

**Comment by ccrraaiigg** [comment]
I have need of this. I've written a webapp for a MIDI device which changes state depending on sequences of multiple control change messages. I'd like to ensure that these sequences are sent atomically, by sending all their data bytes in a single control change message, rather than implementing critical sections around the use of WebMidi.js ports in my app.

I sometimes also send very fast bursts of controller data, and the savings in time and MIDI bandwidth of running status would be significant.

Finally, the official MIDI specification says that all compliant devices must understand running status. The Web MIDI API specification is wrong on that point.

**Comment by djipco** [comment]
WebMidi.js depends on the Web MIDI API implementation of the browser. So, unless the API spec is changed, there isn't much I can do. There is lengthy discussion about this topic that you can refer to for better context:

- https://github.com/WebAudio/web-midi-api/issues/24
- https://github.com/WebAudio/web-midi-api/issues/109#issuecomment-65444947

**Comment by ccrraaiigg** [comment]
Well, as you already mentioned, any layer on top of the Web MIDI API can accommodate messages that use running status, inserting the status bytes behind the scenes. That would at least support porting existing MIDI software to the Web.

I did read those threads before posting. Funny stuff! I love that iOS was cited as a reason not to support a standard feature of MIDI back in 2014, and now iOS doesn't support Web MIDI at all. It's also hilarious that the move to not support running status originated with Yamaha, one of the founding MMA members.

I guess the real question is how things are going with supporting MIDI 2.0. No running status there. :)

Thanks for all your work on this framework!

**Comment by djipco** [comment]
Just to be clear, you can use WebMidi.js to listen for inbound messages using running status. These messages will simply appear as regular 3-byte messages in the input listener. This is the same as Windows MIDI and Core MIDI (macOS and iOS) and actually makes parsing much easier.

What you cannot do with the Web MIDI API is send 2-byte running status messages. Both Core MIDI and USB-MIDI do not support it. Windows MIDI does support it but usually hands the message to an API or transport that doesn't.

One use case which may benefit from using running status is MIDI over Bluetooth Low Energy (BLE-MIDI). However, if I had to guess I would expect BLE-MIDI implementations to do that on their own for performance reasons. The other scenario would be to send data to a a device connected through a 5-pin DIN. But even in this scenario, you would need an API that supports running status and an interface that is not USB-MIDI-based which is rather unlikely.
