### ISSUE TITLE
Notes 6 and 38 are parsed as NRPN messages

### ISSUE THREAD

**Issue by psychedelicious** [djipco/webmidi#91]
Steps to reproduce:
- Send note 6 or 38 on any output: `WebMidi.outputs[0].playNote(6, 1)` or `WebMidi.outputs[0].playNote(38, 1)`:

```
    Uncaught TypeError: Cannot read property 'length' of undefined
        at Input._parseNrpnEvent (webmidi.js:1767)
        at Input._onMidiMessage (webmidi.js:1701)
    Input._parseNrpnEvent @ webmidi.js:1767
    Input._onMidiMessage @ webmidi.js:1701
```

Does not occur in webmidi@2.3.3.

**Comment by psychedelicious** [comment]
I'm not sure if the referenced change causes issue anywhere else and have no experience with NRPN, but it resolves the issue for me and doesn't seem to affect anything else I am doing with webmidi.js.

That said, I noticed that `WebMidi.outputs[0].sendControlChange(6)` (or 38) cause the same error, even with this change to the code. I'm not sure what should happen for CC 6 and 38.

**Comment by djipco** [comment]
@misterinterrupt Do you think you can check this out?

**Comment by djipco** [comment]
This should be a fairly straightforward bug but I cannot seem to be able to reproduce it... Here is the full HTML page I'm using to test the reported issue:

```html
<!DOCTYPE html>

<html lang="en">

  <head>
    <script src="https://cdn.jsdelivr.net/npm/webmidi@2.5.0"></script>
    <script defer>
      WebMidi.enable( error => {
        if(error) console.log("WebMidi Error:", error);
        console.log(WebMidi.outputs);
        WebMidi.outputs[0].playNote(6, 1);
      });
    </script>
  </head>

  <body></body>

</html>
```

Am I missing something obvious? Does this page trigger the error for you @psychedelicious ?

**Comment by misterinterrupt** [comment]
yeah, I'll try to reproduce and see what i can see

**Comment by misterinterrupt** [comment]
I'm not at the computer till a little later today. I'll try to repro and write some integration tests for things too      also, thanks @psychedelicious !

**Comment by psychedelicious** [comment]
Howdy,

Thanks, I have done more testing. That page does reproduce the error for me, but only with a certain setup. 

I think this is only a problem when using the IAC Driver on macOS (virtual MIDI port) for the output port. More testing

Machine 1: 
- macOS 10.14.6 (18G87)
- Chrome 76.0.3809.100 (latest)
- Output:
  - IAC Driver (virtual MIDI) - **error**
  - Ableton Push MK1 - no error
  - Android Phone - no error

Machine 2:
- macOS 10.14 (18A391)
- Chrome 75.0.3770.100
- Output:
  - IAC Driver (virtual MIDI) - **error**

Android phone:
-  Nexus 6P running Android 8.1.0 patch, security patch 5 December 2018
- Chrome 75.0.3770.143
- Output:
  - Built-in native MIDI output - no error

Hmm.

**Comment by djipco** [comment]
This is quite odd...

@misterinterrupt Do you happen to have a Mac to test this?

**Comment by djipco** [comment]
Ok, I looked at it a bit more and it makes sense now. The reason the problem only surfaces when the IAC driver is used is because that virtual MIDI device spits back out what it receives. So, the problem is not the actual `playNote()` code going out the `Output`. The problem is the message coming back into WebMidi.js. 

At line [1765](https://github.com/djipco/webmidi/blob/master/src/webmidi.js#L1765), the `wm._nrpnBuffer[ccEvent.channel]` does not exist yet. So it cannot get the `length` of the array. It would need to be initialized somewhere first. 

This is a serious issue because any inbound **note on** message for note number 6 or 38 will yield an error (even if `nrpnEventsEnabled` is set to `false`).

Unfortunately, I don't have much more time today but perhaps it will help @misterinterrupt in fixing the issue.

**Comment by misterinterrupt** [comment]
Thanks @djipco I do have a mac. Starting on it now.

**Comment by misterinterrupt** [comment]
looks like just initializing the 16 arrays works. I also found out i had a fencepost error on too.

**Comment by misterinterrupt** [comment]
the IAC driver turns out to be super useful for testing the library. I'm testing the fix now and will PR, soon.

**Comment by djipco** [comment]
Awesome! 
You are so right about the IAC driver! I had not realized how useful it could be in a testing scenario until yesterday.

**Comment by misterinterrupt** [comment]
@psychedelicious can you try this code and see if it solves this for you? https://github.com/djipco/webmidi/pull/92

**Comment by psychedelicious** [comment]
@misterinterrupt Confirmed resolved, thank you and @djipco!

**Comment by misterinterrupt** [comment]
heck yeah! Thank you for finding the bug!

**Comment by djipco** [comment]
Thanks to you both! 
I just pushed v2.5.1 to NPM.
