### ISSUE TITLE
Add notes about Web MIDI deprecation on insecure connections

### ISSUE THREAD

**Issue by subesokun** [djipco/webmidi#93]
Hi, while working on some small MIDI demo I came across the issue that in the most recent version of Chrome and Firefox the Web MIDI feature gets disabled on insecure connections (i.e. `window.navigator.requestMIDIAccess` is undefined). I took me a while to figure out why suddenly my demo stopped working and maybe this notice would be also helpful for other developers. Not sure if serving from `localhost` via `HTTP` is also affected by this change.

> [Deprecation] Web MIDI will ask a permission to use even if the sysex is not specified in the MIDIOptions since M77, around September 2019. See https://www.chromestatus.com/feature/5138066234671104 for more details.

Otherwise, keep up with the good work! 👍

**Comment by djipco** [comment]
Thanks for the suggestion. Notes have been added to the README and to the documentation.
